import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  devops: [
    'index',
    {
      type: 'category',
      label: 'Sprints',
      link: { type: 'doc', id: 'sprints/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'sprints',
        },
      ],
    },
    'user-stories/index',
    'user-stories/personas',
    'user-stories/client-user-stories',
    'user-stories/cloud-relay-user-stories',
    'user-stories/devops-user-stores',
    'user-stories/monitoring-user-stories',
    'user-stories/saas-management',
  ],
}

export default sidebars
