version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=SaltKup12()
      - plugins.security.disabled=true
      - http.max_content_length=10MB
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9600:9600
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - SERVER_HOST=0.0.0.0
    ports:
      - 0.0.0.0:5601:5601
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "0.0.0.0:4566:4566"            # main edge port for all services
    environment:
      - SERVICES=dynamodb      # only run DynamoDB (add others comma-separated if needed)
      - DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test
      - DEBUG=1
      - DEFAULT_REGION=ap-southeast-2
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


volumes:
  opensearch-data:

networks:
  opensearch-net:
    driver: bridge

