services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=SaltKup12()
      - plugins.security.disabled=true
      - http.max_content_length=10MB
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - plugins.security.disabled=true
      - OPENSEARCH_PATH_DATA=/data/opensearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/data/opensearch
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9600:9600
    networks:
      - slaops-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - SERVER_HOST=0.0.0.0
    volumes:
      - opensearch-dashboards-data:/data/opensearch-dashboards
    ports:
      - 0.0.0.0:5601:5601
    depends_on:
      - opensearch
    networks:
      - slaops-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '0.0.0.0:4566:4566' # main edge port for all services
    environment:
      - SERVICES=dynamodb,s3 # only run DynamoDB (add others comma-separated if needed)
      - DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test
      - DEBUG=1
      - DATA_DIR=/data/localstack
    volumes:
      # LocalStack internal state
      - ./localstack-data:/data/localstack
      # Init scripts
      - ./localstack/init:/etc/localstack/init/ready.d
      # Docker socket (required for some LocalStack features)
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=slaops
      - PGDATA=/data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - 0.0.0.0:5432:5432
    networks:
      - slaops-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@slaops.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_DEFAULT_USER=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 0.0.0.0:5050:80
    depends_on:
      - postgres
    networks:
      - slaops-network
    user: root

volumes:
  opensearch-data:
  opensearch-dashboards-data:
  postgres-data:
  pgadmin-data:

networks:
  slaops-network:
    driver: bridge
