/* tslint:disable */
/* eslint-disable */
/**
 * Derrops API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { IndexStatsResponseDto } from '../models';
// @ts-ignore
import type { OpenApiSearchResponseDto } from '../models';
// @ts-ignore
import type { ProviderListResponseDto } from '../models';
/**
 * OpenAPISearchApi - axios parameter creator
 */
export const OpenAPISearchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve a specific OpenAPI specification by its ID (format: provider/service/version).
         * @summary Get OpenAPI spec by ID
         * @param {string} id OpenAPI spec ID (URL-encoded, e.g., github.com%2Fapi.github.com%2F1.1.4)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiSearchControllerGetById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('openApiSearchControllerGetById', 'id', id)
            const localVarPath = `/openapi-search/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns aggregate statistics about the indexed OpenAPI specifications.
         * @summary Get index statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiSearchControllerGetStats: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/openapi-search/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of all unique providers/domains with the count of API specs for each.
         * @summary List all API providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiSearchControllerListProviders: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/openapi-search/provider`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search indexed OpenAPI specs by title, description, operations, tags, and more. Supports full-text search and filtering.
         * @summary Search OpenAPI specifications
         * @param {string} [query] Free-text search across title, description, and operation text
         * @param {string} [provider] Filter by provider/domain
         * @param {Array<string>} [tags] Filter by tags (comma-separated)
         * @param {OpenApiSearchControllerSearchMethodEnum} [method] Filter by HTTP method
         * @param {string} [pathPrefix] Filter by path prefix (from operationStats.pathPrefixes)
         * @param {string} [operationId] Filter by exact operationId
         * @param {string} [serverPattern] Filter by server URL pattern
         * @param {number} [from] Pagination offset
         * @param {number} [size] Number of results to return
         * @param {OpenApiSearchControllerSearchSortFieldEnum} [sortField] Sort field
         * @param {OpenApiSearchControllerSearchSortOrderEnum} [sortOrder] Sort order
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiSearchControllerSearch: async (query?: string, provider?: string, tags?: Array<string>, method?: OpenApiSearchControllerSearchMethodEnum, pathPrefix?: string, operationId?: string, serverPattern?: string, from?: number, size?: number, sortField?: OpenApiSearchControllerSearchSortFieldEnum, sortOrder?: OpenApiSearchControllerSearchSortOrderEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/openapi-search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (provider !== undefined) {
                localVarQueryParameter['provider'] = provider;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags;
            }

            if (method !== undefined) {
                localVarQueryParameter['method'] = method;
            }

            if (pathPrefix !== undefined) {
                localVarQueryParameter['pathPrefix'] = pathPrefix;
            }

            if (operationId !== undefined) {
                localVarQueryParameter['operationId'] = operationId;
            }

            if (serverPattern !== undefined) {
                localVarQueryParameter['serverPattern'] = serverPattern;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sortField !== undefined) {
                localVarQueryParameter['sortField'] = sortField;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sortOrder'] = sortOrder;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OpenAPISearchApi - functional programming interface
 */
export const OpenAPISearchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OpenAPISearchApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve a specific OpenAPI specification by its ID (format: provider/service/version).
         * @summary Get OpenAPI spec by ID
         * @param {string} id OpenAPI spec ID (URL-encoded, e.g., github.com%2Fapi.github.com%2F1.1.4)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openApiSearchControllerGetById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openApiSearchControllerGetById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAPISearchApi.openApiSearchControllerGetById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns aggregate statistics about the indexed OpenAPI specifications.
         * @summary Get index statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openApiSearchControllerGetStats(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IndexStatsResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openApiSearchControllerGetStats(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAPISearchApi.openApiSearchControllerGetStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a list of all unique providers/domains with the count of API specs for each.
         * @summary List all API providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openApiSearchControllerListProviders(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProviderListResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openApiSearchControllerListProviders(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAPISearchApi.openApiSearchControllerListProviders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Search indexed OpenAPI specs by title, description, operations, tags, and more. Supports full-text search and filtering.
         * @summary Search OpenAPI specifications
         * @param {string} [query] Free-text search across title, description, and operation text
         * @param {string} [provider] Filter by provider/domain
         * @param {Array<string>} [tags] Filter by tags (comma-separated)
         * @param {OpenApiSearchControllerSearchMethodEnum} [method] Filter by HTTP method
         * @param {string} [pathPrefix] Filter by path prefix (from operationStats.pathPrefixes)
         * @param {string} [operationId] Filter by exact operationId
         * @param {string} [serverPattern] Filter by server URL pattern
         * @param {number} [from] Pagination offset
         * @param {number} [size] Number of results to return
         * @param {OpenApiSearchControllerSearchSortFieldEnum} [sortField] Sort field
         * @param {OpenApiSearchControllerSearchSortOrderEnum} [sortOrder] Sort order
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openApiSearchControllerSearch(query?: string, provider?: string, tags?: Array<string>, method?: OpenApiSearchControllerSearchMethodEnum, pathPrefix?: string, operationId?: string, serverPattern?: string, from?: number, size?: number, sortField?: OpenApiSearchControllerSearchSortFieldEnum, sortOrder?: OpenApiSearchControllerSearchSortOrderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OpenApiSearchResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openApiSearchControllerSearch(query, provider, tags, method, pathPrefix, operationId, serverPattern, from, size, sortField, sortOrder, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAPISearchApi.openApiSearchControllerSearch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OpenAPISearchApi - factory interface
 */
export const OpenAPISearchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OpenAPISearchApiFp(configuration)
    return {
        /**
         * Retrieve a specific OpenAPI specification by its ID (format: provider/service/version).
         * @summary Get OpenAPI spec by ID
         * @param {string} id OpenAPI spec ID (URL-encoded, e.g., github.com%2Fapi.github.com%2F1.1.4)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiSearchControllerGetById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.openApiSearchControllerGetById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns aggregate statistics about the indexed OpenAPI specifications.
         * @summary Get index statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiSearchControllerGetStats(options?: RawAxiosRequestConfig): AxiosPromise<IndexStatsResponseDto> {
            return localVarFp.openApiSearchControllerGetStats(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of all unique providers/domains with the count of API specs for each.
         * @summary List all API providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiSearchControllerListProviders(options?: RawAxiosRequestConfig): AxiosPromise<Array<ProviderListResponseDto>> {
            return localVarFp.openApiSearchControllerListProviders(options).then((request) => request(axios, basePath));
        },
        /**
         * Search indexed OpenAPI specs by title, description, operations, tags, and more. Supports full-text search and filtering.
         * @summary Search OpenAPI specifications
         * @param {string} [query] Free-text search across title, description, and operation text
         * @param {string} [provider] Filter by provider/domain
         * @param {Array<string>} [tags] Filter by tags (comma-separated)
         * @param {OpenApiSearchControllerSearchMethodEnum} [method] Filter by HTTP method
         * @param {string} [pathPrefix] Filter by path prefix (from operationStats.pathPrefixes)
         * @param {string} [operationId] Filter by exact operationId
         * @param {string} [serverPattern] Filter by server URL pattern
         * @param {number} [from] Pagination offset
         * @param {number} [size] Number of results to return
         * @param {OpenApiSearchControllerSearchSortFieldEnum} [sortField] Sort field
         * @param {OpenApiSearchControllerSearchSortOrderEnum} [sortOrder] Sort order
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiSearchControllerSearch(query?: string, provider?: string, tags?: Array<string>, method?: OpenApiSearchControllerSearchMethodEnum, pathPrefix?: string, operationId?: string, serverPattern?: string, from?: number, size?: number, sortField?: OpenApiSearchControllerSearchSortFieldEnum, sortOrder?: OpenApiSearchControllerSearchSortOrderEnum, options?: RawAxiosRequestConfig): AxiosPromise<OpenApiSearchResponseDto> {
            return localVarFp.openApiSearchControllerSearch(query, provider, tags, method, pathPrefix, operationId, serverPattern, from, size, sortField, sortOrder, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OpenAPISearchApi - object-oriented interface
 */
export class OpenAPISearchApi extends BaseAPI {
    /**
     * Retrieve a specific OpenAPI specification by its ID (format: provider/service/version).
     * @summary Get OpenAPI spec by ID
     * @param {string} id OpenAPI spec ID (URL-encoded, e.g., github.com%2Fapi.github.com%2F1.1.4)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public openApiSearchControllerGetById(id: string, options?: RawAxiosRequestConfig) {
        return OpenAPISearchApiFp(this.configuration).openApiSearchControllerGetById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns aggregate statistics about the indexed OpenAPI specifications.
     * @summary Get index statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public openApiSearchControllerGetStats(options?: RawAxiosRequestConfig) {
        return OpenAPISearchApiFp(this.configuration).openApiSearchControllerGetStats(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of all unique providers/domains with the count of API specs for each.
     * @summary List all API providers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public openApiSearchControllerListProviders(options?: RawAxiosRequestConfig) {
        return OpenAPISearchApiFp(this.configuration).openApiSearchControllerListProviders(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search indexed OpenAPI specs by title, description, operations, tags, and more. Supports full-text search and filtering.
     * @summary Search OpenAPI specifications
     * @param {string} [query] Free-text search across title, description, and operation text
     * @param {string} [provider] Filter by provider/domain
     * @param {Array<string>} [tags] Filter by tags (comma-separated)
     * @param {OpenApiSearchControllerSearchMethodEnum} [method] Filter by HTTP method
     * @param {string} [pathPrefix] Filter by path prefix (from operationStats.pathPrefixes)
     * @param {string} [operationId] Filter by exact operationId
     * @param {string} [serverPattern] Filter by server URL pattern
     * @param {number} [from] Pagination offset
     * @param {number} [size] Number of results to return
     * @param {OpenApiSearchControllerSearchSortFieldEnum} [sortField] Sort field
     * @param {OpenApiSearchControllerSearchSortOrderEnum} [sortOrder] Sort order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public openApiSearchControllerSearch(query?: string, provider?: string, tags?: Array<string>, method?: OpenApiSearchControllerSearchMethodEnum, pathPrefix?: string, operationId?: string, serverPattern?: string, from?: number, size?: number, sortField?: OpenApiSearchControllerSearchSortFieldEnum, sortOrder?: OpenApiSearchControllerSearchSortOrderEnum, options?: RawAxiosRequestConfig) {
        return OpenAPISearchApiFp(this.configuration).openApiSearchControllerSearch(query, provider, tags, method, pathPrefix, operationId, serverPattern, from, size, sortField, sortOrder, options).then((request) => request(this.axios, this.basePath));
    }
}

export const OpenApiSearchControllerSearchMethodEnum = {
    Get: 'GET',
    Post: 'POST',
    Put: 'PUT',
    Delete: 'DELETE',
    Patch: 'PATCH',
    Head: 'HEAD',
    Options: 'OPTIONS'
} as const;
export type OpenApiSearchControllerSearchMethodEnum = typeof OpenApiSearchControllerSearchMethodEnum[keyof typeof OpenApiSearchControllerSearchMethodEnum];
export const OpenApiSearchControllerSearchSortFieldEnum = {
    Title: 'title',
    Provider: 'provider',
    IndexedAt: 'indexedAt',
    OperationStatsTotal: 'operationStats.total',
    Score: '_score'
} as const;
export type OpenApiSearchControllerSearchSortFieldEnum = typeof OpenApiSearchControllerSearchSortFieldEnum[keyof typeof OpenApiSearchControllerSearchSortFieldEnum];
export const OpenApiSearchControllerSearchSortOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type OpenApiSearchControllerSearchSortOrderEnum = typeof OpenApiSearchControllerSearchSortOrderEnum[keyof typeof OpenApiSearchControllerSearchSortOrderEnum];
