/* tslint:disable */
/* eslint-disable */
/**
 * Derrops API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateServiceDto } from '../models';
// @ts-ignore
import type { Service } from '../models';
// @ts-ignore
import type { ServiceControllerRemove200Response } from '../models';
// @ts-ignore
import type { UpdateServiceDto } from '../models';
/**
 * ServiceApi - axios parameter creator
 */
export const ServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new service
         * @param {CreateServiceDto} createServiceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        serviceControllerCreate: async (createServiceDto: CreateServiceDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createServiceDto' is not null or undefined
            assertParamExists('serviceControllerCreate', 'createServiceDto', createServiceDto)
            const localVarPath = `/services`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createServiceDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all services
         * @param {string} [select] Comma-separated list of fields to select (e.g., id,name,endpoint)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        serviceControllerFindAll: async (select?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/services`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (select !== undefined) {
                localVarQueryParameter['select'] = select;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a service by ID
         * @param {string} id Service UUID
         * @param {string} [select] Comma-separated list of fields to select
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        serviceControllerFindOne: async (id: string, select?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('serviceControllerFindOne', 'id', id)
            const localVarPath = `/services/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (select !== undefined) {
                localVarQueryParameter['select'] = select;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a service
         * @param {string} id Service UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        serviceControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('serviceControllerRemove', 'id', id)
            const localVarPath = `/services/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a service
         * @param {string} id Service UUID
         * @param {UpdateServiceDto} updateServiceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        serviceControllerUpdate: async (id: string, updateServiceDto: UpdateServiceDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('serviceControllerUpdate', 'id', id)
            // verify required parameter 'updateServiceDto' is not null or undefined
            assertParamExists('serviceControllerUpdate', 'updateServiceDto', updateServiceDto)
            const localVarPath = `/services/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateServiceDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServiceApi - functional programming interface
 */
export const ServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new service
         * @param {CreateServiceDto} createServiceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async serviceControllerCreate(createServiceDto: CreateServiceDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Service>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.serviceControllerCreate(createServiceDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServiceApi.serviceControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all services
         * @param {string} [select] Comma-separated list of fields to select (e.g., id,name,endpoint)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async serviceControllerFindAll(select?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Service>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.serviceControllerFindAll(select, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServiceApi.serviceControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a service by ID
         * @param {string} id Service UUID
         * @param {string} [select] Comma-separated list of fields to select
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async serviceControllerFindOne(id: string, select?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Service>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.serviceControllerFindOne(id, select, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServiceApi.serviceControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a service
         * @param {string} id Service UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async serviceControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ServiceControllerRemove200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.serviceControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServiceApi.serviceControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a service
         * @param {string} id Service UUID
         * @param {UpdateServiceDto} updateServiceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async serviceControllerUpdate(id: string, updateServiceDto: UpdateServiceDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Service>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.serviceControllerUpdate(id, updateServiceDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServiceApi.serviceControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ServiceApi - factory interface
 */
export const ServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServiceApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new service
         * @param {CreateServiceDto} createServiceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        serviceControllerCreate(createServiceDto: CreateServiceDto, options?: RawAxiosRequestConfig): AxiosPromise<Service> {
            return localVarFp.serviceControllerCreate(createServiceDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all services
         * @param {string} [select] Comma-separated list of fields to select (e.g., id,name,endpoint)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        serviceControllerFindAll(select?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<Service>> {
            return localVarFp.serviceControllerFindAll(select, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a service by ID
         * @param {string} id Service UUID
         * @param {string} [select] Comma-separated list of fields to select
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        serviceControllerFindOne(id: string, select?: string, options?: RawAxiosRequestConfig): AxiosPromise<Service> {
            return localVarFp.serviceControllerFindOne(id, select, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a service
         * @param {string} id Service UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        serviceControllerRemove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ServiceControllerRemove200Response> {
            return localVarFp.serviceControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a service
         * @param {string} id Service UUID
         * @param {UpdateServiceDto} updateServiceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        serviceControllerUpdate(id: string, updateServiceDto: UpdateServiceDto, options?: RawAxiosRequestConfig): AxiosPromise<Service> {
            return localVarFp.serviceControllerUpdate(id, updateServiceDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ServiceApi - object-oriented interface
 */
export class ServiceApi extends BaseAPI {
    /**
     * 
     * @summary Create a new service
     * @param {CreateServiceDto} createServiceDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public serviceControllerCreate(createServiceDto: CreateServiceDto, options?: RawAxiosRequestConfig) {
        return ServiceApiFp(this.configuration).serviceControllerCreate(createServiceDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all services
     * @param {string} [select] Comma-separated list of fields to select (e.g., id,name,endpoint)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public serviceControllerFindAll(select?: string, options?: RawAxiosRequestConfig) {
        return ServiceApiFp(this.configuration).serviceControllerFindAll(select, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a service by ID
     * @param {string} id Service UUID
     * @param {string} [select] Comma-separated list of fields to select
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public serviceControllerFindOne(id: string, select?: string, options?: RawAxiosRequestConfig) {
        return ServiceApiFp(this.configuration).serviceControllerFindOne(id, select, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a service
     * @param {string} id Service UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public serviceControllerRemove(id: string, options?: RawAxiosRequestConfig) {
        return ServiceApiFp(this.configuration).serviceControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a service
     * @param {string} id Service UUID
     * @param {UpdateServiceDto} updateServiceDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public serviceControllerUpdate(id: string, updateServiceDto: UpdateServiceDto, options?: RawAxiosRequestConfig) {
        return ServiceApiFp(this.configuration).serviceControllerUpdate(id, updateServiceDto, options).then((request) => request(this.axios, this.basePath));
    }
}

