/* tslint:disable */
/* eslint-disable */
/**
 * Derrops API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
import type { Configuration } from '../configuration'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setSearchParams,
  toPathString,
} from '../common'
// @ts-ignore
import { BASE_PATH, BaseAPI, RequiredError, operationServerMap, type RequestArgs } from '../base'
// @ts-ignore
import type { CreateServiceDto } from '../models'
// @ts-ignore
import type { Service } from '../models'
// @ts-ignore
import type { ServicesControllerRemove200Response } from '../models'
// @ts-ignore
import type { UpdateServiceDto } from '../models'
/**
 * ServiceApi - axios parameter creator
 */
export const ServiceApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Create a new service
     * @param {CreateServiceDto} createServiceDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    servicesControllerCreate: async (
      createServiceDto: CreateServiceDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createServiceDto' is not null or undefined
      assertParamExists('servicesControllerCreate', 'createServiceDto', createServiceDto)
      const localVarPath = `/services`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'
      localVarHeaderParameter['Accept'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        createServiceDto,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Get all services
     * @param {string} [select] Comma-separated list of fields to select (e.g., id,name,endpoint)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    servicesControllerFindAll: async (
      select?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/services`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      if (select !== undefined) {
        localVarQueryParameter['select'] = select
      }

      localVarHeaderParameter['Accept'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Get a service by ID
     * @param {string} id Service UUID
     * @param {string} [select] Comma-separated list of fields to select
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    servicesControllerFindOne: async (
      id: string,
      select?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('servicesControllerFindOne', 'id', id)
      const localVarPath = `/services/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      if (select !== undefined) {
        localVarQueryParameter['select'] = select
      }

      localVarHeaderParameter['Accept'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Delete a service
     * @param {string} id Service UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    servicesControllerRemove: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('servicesControllerRemove', 'id', id)
      const localVarPath = `/services/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Accept'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Update a service
     * @param {string} id Service UUID
     * @param {UpdateServiceDto} updateServiceDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    servicesControllerUpdate: async (
      id: string,
      updateServiceDto: UpdateServiceDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('servicesControllerUpdate', 'id', id)
      // verify required parameter 'updateServiceDto' is not null or undefined
      assertParamExists('servicesControllerUpdate', 'updateServiceDto', updateServiceDto)
      const localVarPath = `/services/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'
      localVarHeaderParameter['Accept'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateServiceDto,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * ServiceApi - functional programming interface
 */
export const ServiceApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ServiceApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @summary Create a new service
     * @param {CreateServiceDto} createServiceDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async servicesControllerCreate(
      createServiceDto: CreateServiceDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Service>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.servicesControllerCreate(
        createServiceDto,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ServiceApi.servicesControllerCreate']?.[localVarOperationServerIndex]
          ?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Get all services
     * @param {string} [select] Comma-separated list of fields to select (e.g., id,name,endpoint)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async servicesControllerFindAll(
      select?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Service>>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.servicesControllerFindAll(
        select,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ServiceApi.servicesControllerFindAll']?.[localVarOperationServerIndex]
          ?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Get a service by ID
     * @param {string} id Service UUID
     * @param {string} [select] Comma-separated list of fields to select
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async servicesControllerFindOne(
      id: string,
      select?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Service>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.servicesControllerFindOne(
        id,
        select,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ServiceApi.servicesControllerFindOne']?.[localVarOperationServerIndex]
          ?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Delete a service
     * @param {string} id Service UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async servicesControllerRemove(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ServicesControllerRemove200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.servicesControllerRemove(
        id,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ServiceApi.servicesControllerRemove']?.[localVarOperationServerIndex]
          ?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Update a service
     * @param {string} id Service UUID
     * @param {UpdateServiceDto} updateServiceDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async servicesControllerUpdate(
      id: string,
      updateServiceDto: UpdateServiceDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Service>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.servicesControllerUpdate(
        id,
        updateServiceDto,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ServiceApi.servicesControllerUpdate']?.[localVarOperationServerIndex]
          ?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * ServiceApi - factory interface
 */
export const ServiceApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ServiceApiFp(configuration)
  return {
    /**
     *
     * @summary Create a new service
     * @param {CreateServiceDto} createServiceDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    servicesControllerCreate(
      createServiceDto: CreateServiceDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Service> {
      return localVarFp
        .servicesControllerCreate(createServiceDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Get all services
     * @param {string} [select] Comma-separated list of fields to select (e.g., id,name,endpoint)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    servicesControllerFindAll(
      select?: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<Service>> {
      return localVarFp
        .servicesControllerFindAll(select, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Get a service by ID
     * @param {string} id Service UUID
     * @param {string} [select] Comma-separated list of fields to select
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    servicesControllerFindOne(
      id: string,
      select?: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Service> {
      return localVarFp
        .servicesControllerFindOne(id, select, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Delete a service
     * @param {string} id Service UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    servicesControllerRemove(
      id: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ServicesControllerRemove200Response> {
      return localVarFp
        .servicesControllerRemove(id, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Update a service
     * @param {string} id Service UUID
     * @param {UpdateServiceDto} updateServiceDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    servicesControllerUpdate(
      id: string,
      updateServiceDto: UpdateServiceDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Service> {
      return localVarFp
        .servicesControllerUpdate(id, updateServiceDto, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * ServiceApi - object-oriented interface
 */
export class ServiceApi extends BaseAPI {
  /**
   *
   * @summary Create a new service
   * @param {CreateServiceDto} createServiceDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public servicesControllerCreate(
    createServiceDto: CreateServiceDto,
    options?: RawAxiosRequestConfig,
  ) {
    return ServiceApiFp(this.configuration)
      .servicesControllerCreate(createServiceDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Get all services
   * @param {string} [select] Comma-separated list of fields to select (e.g., id,name,endpoint)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public servicesControllerFindAll(select?: string, options?: RawAxiosRequestConfig) {
    return ServiceApiFp(this.configuration)
      .servicesControllerFindAll(select, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Get a service by ID
   * @param {string} id Service UUID
   * @param {string} [select] Comma-separated list of fields to select
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public servicesControllerFindOne(id: string, select?: string, options?: RawAxiosRequestConfig) {
    return ServiceApiFp(this.configuration)
      .servicesControllerFindOne(id, select, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Delete a service
   * @param {string} id Service UUID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public servicesControllerRemove(id: string, options?: RawAxiosRequestConfig) {
    return ServiceApiFp(this.configuration)
      .servicesControllerRemove(id, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Update a service
   * @param {string} id Service UUID
   * @param {UpdateServiceDto} updateServiceDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public servicesControllerUpdate(
    id: string,
    updateServiceDto: UpdateServiceDto,
    options?: RawAxiosRequestConfig,
  ) {
    return ServiceApiFp(this.configuration)
      .servicesControllerUpdate(id, updateServiceDto, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
