import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  'platform-design': [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
}

export default sidebars
