/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AegisRegisterDto {
  /**
   * One-time registration token issued when the Aegis instance was created
   */
  registrationToken: string
  /**
   * JWKS endpoint URL of the Aegis instance (must be HTTPS)
   */
  jwksUrl: string
}
