/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CloudRelayJob {
    'id': string;
    'connection_id': string;
    'tenant_id': string;
    'user_id': string;
    'delivery_mode': CloudRelayJobDeliveryModeEnum;
    'status': CloudRelayJobStatusEnum;
    /**
     * Full CloudProxyRequestDto payload. Stored for platform-queue (relay reads it when claiming) and direct mode. Null for relay-queue (relay owns the request data).
     */
    'request'?: object | null;
    /**
     * Relay-internal job ID. Set for relay-queue mode only.
     */
    'relay_job_id'?: string | null;
    /**
     * CloudProxyResponseDto or CloudProxyErrorDto. Set once job completes.
     */
    'result'?: object | null;
    'claimed_at'?: string | null;
    'completed_at'?: string | null;
    'created_at': string;
    'expires_at': string;
}

export const CloudRelayJobDeliveryModeEnum = {
    Direct: 'direct',
    RelayQueue: 'relay-queue',
    PlatformQueue: 'platform-queue',
    Hybrid: 'hybrid'
} as const;

export type CloudRelayJobDeliveryModeEnum = typeof CloudRelayJobDeliveryModeEnum[keyof typeof CloudRelayJobDeliveryModeEnum];
export const CloudRelayJobStatusEnum = {
    Pending: 'pending',
    Claimed: 'claimed',
    Completed: 'completed',
    Failed: 'failed'
} as const;

export type CloudRelayJobStatusEnum = typeof CloudRelayJobStatusEnum[keyof typeof CloudRelayJobStatusEnum];


