/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CloudRelayConnection {
    'id': string;
    'tenant_id': string;
    'name': string;
    /**
     * Base URL of the relay instance. Used for direct and relay-queue modes. For platform-queue mode, the relay is not called inbound — leave this as the relay identifier URL.
     */
    'url': string;
    /**
     * managed     — SLAOps-hosted Lambda relay. self-hosted — Customer-deployed relay on their own infrastructure. local-dev   — Developer local machine. delivery_mode is locked to platform-queue. An SQS FIFO queue is provisioned automatically.
     */
    'type': CloudRelayConnectionTypeEnum;
    /**
     * direct         — slaops-cloud calls relay synchronously. Relay must be reachable from slaops-cloud. relay-queue    — slaops-cloud submits to relay queue, polls relay for result. Relay must be reachable from slaops-cloud. platform-queue — relay polls slaops-cloud outbound and posts results back. Use when relay cannot accept inbound connections.
     */
    'delivery_mode': CloudRelayConnectionDeliveryModeEnum;
    /**
     * platform — SLAOps provisions and owns the SQS FIFO queue (default for local-dev). relay    — Customer provisions the queue in their own AWS account and grants the SlaOpsSqsPublishRole SendMessage access. Use relay mode when the customer\'s network cannot reach SQS endpoints in the SLAOps account.
     */
    'sqs_queue_mode'?: CloudRelayConnectionSqsQueueModeEnum;
    /**
     * SQS FIFO queue URL for this relay connection. platform mode: provisioned by slaops-cloud and stored here. relay mode: provided by the customer at registration time.
     */
    'sqs_queue_url'?: string | null;
    /**
     * AWS region of the SQS queue.
     */
    'sqs_region'?: string | null;
    /**
     * API key for relay authentication. direct/relay-queue: slaops-cloud sends this as Bearer token to the relay. platform-queue: relay sends this as Bearer token when polling slaops-cloud. Configure the relay with RELAY_API_KEY (inbound) or RELAY_PLATFORM_TOKEN (outbound polling).
     */
    'api_key': string;
    'created_at': string;
    'updated_at': string;
}

export const CloudRelayConnectionTypeEnum = {
    Managed: 'managed',
    SelfHosted: 'self-hosted',
    LocalDev: 'local-dev'
} as const;

export type CloudRelayConnectionTypeEnum = typeof CloudRelayConnectionTypeEnum[keyof typeof CloudRelayConnectionTypeEnum];
export const CloudRelayConnectionDeliveryModeEnum = {
    Direct: 'direct',
    RelayQueue: 'relay-queue',
    PlatformQueue: 'platform-queue'
} as const;

export type CloudRelayConnectionDeliveryModeEnum = typeof CloudRelayConnectionDeliveryModeEnum[keyof typeof CloudRelayConnectionDeliveryModeEnum];
export const CloudRelayConnectionSqsQueueModeEnum = {
    Platform: 'platform',
    Relay: 'relay'
} as const;

export type CloudRelayConnectionSqsQueueModeEnum = typeof CloudRelayConnectionSqsQueueModeEnum[keyof typeof CloudRelayConnectionSqsQueueModeEnum];


