/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateCloudRelayConnectionDto {
  /**
   * managed     — SLAOps-hosted Lambda relay. self-hosted — Customer-deployed relay on their own infrastructure. local-dev   — Developer local machine. delivery_mode is locked to platform-queue and an SQS FIFO queue is provisioned automatically.
   */
  type?: CreateCloudRelayConnectionDtoTypeEnum
  /**
   * Human-readable name. Auto-generated if omitted.
   */
  name?: string
  /**
   * Base URL of the relay instance. Required for direct and relay-queue modes, and for the HTTP path in hybrid mode. Not used for platform-queue connections (relay makes only outbound connections).
   */
  url?: string
  /**
   * direct          — slaops-cloud calls relay synchronously. relay-queue     — slaops-cloud submits to relay queue, polls relay for result. platform-queue  — relay polls slaops-cloud outbound. Use when relay cannot accept inbound connections. hybrid          — platform tries direct HTTP first, falls back to SQS on failure. Requires both url and sqs_queue_url. For local-dev relays this is always platform-queue regardless of what is sent.
   */
  delivery_mode?: CreateCloudRelayConnectionDtoDeliveryModeEnum
  /**
   * platform — SLAOps provisions and owns the SQS FIFO queue. relay    — Customer provisions the queue and grants sqs:SendMessage to the SLAOps platform role; provide relay_sqs_queue_url. Required when delivery_mode is platform-queue or hybrid.
   */
  sqs_queue_mode?: CreateCloudRelayConnectionDtoSqsQueueModeEnum
  /**
   * Customer-owned SQS FIFO queue URL. Required when sqs_queue_mode=relay. The customer must grant the SlaOpsSqsPublishRole sqs:SendMessage permission on this queue.
   */
  relay_sqs_queue_url?: string
  /**
   * UUID of an AegisInstance to link to this connection. The Aegis must belong to the same tenant. Null or omitted means no Aegis is linked.
   */
  aegis_id?: string
}

export const CreateCloudRelayConnectionDtoTypeEnum = {
  Managed: 'managed',
  SelfHosted: 'self-hosted',
  LocalDev: 'local-dev',
} as const

export type CreateCloudRelayConnectionDtoTypeEnum =
  (typeof CreateCloudRelayConnectionDtoTypeEnum)[keyof typeof CreateCloudRelayConnectionDtoTypeEnum]
export const CreateCloudRelayConnectionDtoDeliveryModeEnum = {
  Direct: 'direct',
  RelayQueue: 'relay-queue',
  PlatformQueue: 'platform-queue',
  Hybrid: 'hybrid',
} as const

export type CreateCloudRelayConnectionDtoDeliveryModeEnum =
  (typeof CreateCloudRelayConnectionDtoDeliveryModeEnum)[keyof typeof CreateCloudRelayConnectionDtoDeliveryModeEnum]
export const CreateCloudRelayConnectionDtoSqsQueueModeEnum = {
  Platform: 'platform',
  Relay: 'relay',
} as const

export type CreateCloudRelayConnectionDtoSqsQueueModeEnum =
  (typeof CreateCloudRelayConnectionDtoSqsQueueModeEnum)[keyof typeof CreateCloudRelayConnectionDtoSqsQueueModeEnum]
