/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface IndexStatsResponseDto {
    /**
     * Total indexed documents
     */
    'totalDocuments': number;
    /**
     * Total operations across all specs
     */
    'totalOperations': number;
    /**
     * Number of unique providers
     */
    'uniqueProviders': number;
    /**
     * Number of unique tags
     */
    'uniqueTags': number;
    /**
     * Last indexed timestamp
     */
    'lastIndexedAt'?: string;
}

