/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OpenApiSearchHit {
  /**
   * The matched document
   */
  document: object
  /**
   * Search relevance score
   */
  score: number
  /**
   * Highlighted matches
   */
  highlights?: object
}
