/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OpenApiSearchHit } from './open-api-search-hit';
// May contain unused imports in some cases
// @ts-ignore
import type { SearchAggregations } from './search-aggregations';

export interface OpenApiSearchResponseDto {
    /**
     * Total matching documents
     */
    'total': number;
    /**
     * Search hits
     */
    'hits': Array<OpenApiSearchHit>;
    /**
     * Aggregations/facets
     */
    'aggregations'?: SearchAggregations;
    /**
     * Query execution time in milliseconds
     */
    'took': number;
}

