/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VersionFetchState {
  /**
   * manual    — spec is uploaded manually via the portal or pre-signed URL. url_fetch — platform fetches the spec from fetch_url on a schedule.
   */
  strategy?: VersionFetchStateStrategyEnum
  /**
   * URL the platform fetches the spec from (url_fetch strategy only). Must be publicly accessible or reachable from the SLAOps egress IP range.
   */
  url?: string
  /**
   * Cron expression defining the fetch schedule (url_fetch strategy only). Defaults to config[oaspec.url-fetch.default-cron] when not specified.
   */
  cron?: string
  /**
   * Timestamp of the last fetch attempt
   */
  lastAt?: string
  /**
   * Outcome of the last fetch attempt
   */
  lastStatus?: VersionFetchStateLastStatusEnum
  /**
   * Error message from the last failed fetch attempt
   */
  lastError?: string
  /**
   * Consecutive fetch failure count. When this reaches config[oaspec.url-fetch.backoff-threshold] the scheduler reduces to weekly cadence.
   */
  consecutiveFailures?: number
}

export const VersionFetchStateStrategyEnum = {
  Manual: 'manual',
  UrlFetch: 'url_fetch',
} as const

export type VersionFetchStateStrategyEnum =
  (typeof VersionFetchStateStrategyEnum)[keyof typeof VersionFetchStateStrategyEnum]
export const VersionFetchStateLastStatusEnum = {
  Ok: 'ok',
  Error: 'error',
  NoChange: 'no_change',
} as const

export type VersionFetchStateLastStatusEnum =
  (typeof VersionFetchStateLastStatusEnum)[keyof typeof VersionFetchStateLastStatusEnum]
