/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateCloudRelayConnectionDto {
    /**
     * managed     — SLAOps-hosted Lambda relay. self-hosted — Customer-deployed relay on their own infrastructure. local-dev   — Developer local machine. delivery_mode is locked to platform-queue and an SQS FIFO queue is provisioned automatically.
     */
    'type'?: CreateCloudRelayConnectionDtoTypeEnum;
    /**
     * Human-readable name. Auto-generated for local-dev relays.
     */
    'name'?: string;
    /**
     * Base URL of the relay instance. Required for direct and relay-queue modes. Not used for platform-queue / local-dev relays (relay makes only outbound connections).
     */
    'url'?: string;
    /**
     * platform — SLAOps provisions the SQS FIFO queue (default). relay    — Customer provisions the queue; provide relay_sqs_queue_url. Only relevant for local-dev relay connections.
     */
    'sqs_queue_mode'?: CreateCloudRelayConnectionDtoSqsQueueModeEnum;
    /**
     * Customer-owned SQS FIFO queue URL. Required when sqs_queue_mode=relay. The customer must grant the SlaOpsSqsPublishRole sqs:SendMessage permission on this queue.
     */
    'relay_sqs_queue_url'?: string;
    /**
     * direct          — slaops-cloud calls relay synchronously. Relay must be reachable from slaops-cloud. relay-queue     — slaops-cloud submits to relay queue, polls relay for result. Relay must be reachable from slaops-cloud. platform-queue  — relay polls slaops-cloud outbound and posts results back. Use when relay cannot accept inbound connections. For local-dev relays this is always platform-queue regardless of what is sent.
     */
    'delivery_mode'?: CreateCloudRelayConnectionDtoDeliveryModeEnum;
}

export const CreateCloudRelayConnectionDtoTypeEnum = {
    Managed: 'managed',
    SelfHosted: 'self-hosted',
    LocalDev: 'local-dev'
} as const;

export type CreateCloudRelayConnectionDtoTypeEnum = typeof CreateCloudRelayConnectionDtoTypeEnum[keyof typeof CreateCloudRelayConnectionDtoTypeEnum];
export const CreateCloudRelayConnectionDtoSqsQueueModeEnum = {
    Platform: 'platform',
    Relay: 'relay'
} as const;

export type CreateCloudRelayConnectionDtoSqsQueueModeEnum = typeof CreateCloudRelayConnectionDtoSqsQueueModeEnum[keyof typeof CreateCloudRelayConnectionDtoSqsQueueModeEnum];
export const CreateCloudRelayConnectionDtoDeliveryModeEnum = {
    Direct: 'direct',
    RelayQueue: 'relay-queue',
    PlatformQueue: 'platform-queue'
} as const;

export type CreateCloudRelayConnectionDtoDeliveryModeEnum = typeof CreateCloudRelayConnectionDtoDeliveryModeEnum[keyof typeof CreateCloudRelayConnectionDtoDeliveryModeEnum];


