/* tslint:disable */
/* eslint-disable */
/**
 * Derrops API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AegisCreateResponseDto {
    'id': string;
    'tenant_id': string;
    'name': string;
    'url': string;
    'jwks_url': string;
    'status': string;
    'created_at': string;
    'updated_at': string;
    /**
     * One-time registration token — configure Aegis with this value. Not stored in plaintext.
     */
    'registrationToken': string;
}

