/* tslint:disable */
/* eslint-disable */
/**
 * Derrops API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateCloudRelayConnectionResponseDto {
    'id': string;
    'tenant_id': string;
    'name': string;
    /**
     * Base URL of the relay instance. Used for direct and relay-queue modes. For platform-queue mode, the relay is not called inbound — leave this as the relay identifier URL.
     */
    'url': string;
    /**
     * managed     — Derrops-hosted Lambda relay. self-hosted — Customer-deployed relay on their own infrastructure. local-dev   — Developer local machine. delivery_mode is locked to platform-queue. An SQS FIFO queue is provisioned automatically.
     */
    'type': CreateCloudRelayConnectionResponseDtoTypeEnum;
    /**
     * direct         — derrops-cloud calls relay synchronously. Relay must be reachable from derrops-cloud. relay-queue    — derrops-cloud submits to relay queue, polls relay for result. Relay must be reachable from derrops-cloud. platform-queue — relay polls derrops-cloud outbound and posts results back. Use when relay cannot accept inbound connections. hybrid         — platform tries direct HTTP first; falls back to platform-queue on failure. Requires both url and sqs_queue_url.
     */
    'delivery_mode': CreateCloudRelayConnectionResponseDtoDeliveryModeEnum;
    /**
     * platform — Derrops provisions and owns the SQS FIFO queue (default for local-dev). relay    — Customer provisions the queue in their own AWS account and grants the DerropsSqsPublishRole SendMessage access. Use relay mode when the customer\'s network cannot reach SQS endpoints in the Derrops account.
     */
    'sqs_queue_mode'?: CreateCloudRelayConnectionResponseDtoSqsQueueModeEnum;
    /**
     * SQS FIFO queue URL for this relay connection. platform mode: provisioned by derrops-cloud and stored here. relay mode: provided by the customer at registration time.
     */
    'sqs_queue_url'?: string | null;
    /**
     * AWS region of the SQS queue.
     */
    'sqs_region'?: string | null;
    /**
     * UUID of the linked AegisInstance. Optional — null means no Aegis for this connection.
     */
    'aegis_id'?: string | null;
    /**
     * ARN of the IAM user provisioned for relay SQS queue access (sqs_queue_mode=platform only). Null until IAM provisioning is implemented.
     */
    'iam_user_arn'?: string | null;
    /**
     * Access key ID of the IAM credential created for the relay. Stored for operator reference only — the secret access key is never stored.
     */
    'iam_access_key_id'?: string | null;
    /**
     * API key for relay authentication. direct/relay-queue: derrops-cloud sends this as Bearer token to the relay. platform-queue: relay sends this as Bearer token when polling derrops-cloud. Configure the relay with RELAY_API_KEY (inbound) or RELAY_PLATFORM_TOKEN (outbound polling).
     */
    'api_key': string;
    'created_at': string;
    'updated_at': string;
    /**
     * IAM access key ID for the provisioned relay IAM user (sqs_queue_mode=platform only). Returned once — not stored. Null until IAM provisioning is implemented.
     */
    'iam_access_key_id_created'?: string;
    /**
     * IAM secret access key for the provisioned relay IAM user (sqs_queue_mode=platform only). Returned once — never stored. Null until IAM provisioning is implemented.
     */
    'iam_secret_access_key'?: string;
    /**
     * One-time Aegis registration token, returned only when a new Aegis instance was registered as part of this connection creation. Never returned again.
     */
    'aegis_registration_token'?: string;
}

export const CreateCloudRelayConnectionResponseDtoTypeEnum = {
    Managed: 'managed',
    SelfHosted: 'self-hosted',
    LocalDev: 'local-dev'
} as const;

export type CreateCloudRelayConnectionResponseDtoTypeEnum = typeof CreateCloudRelayConnectionResponseDtoTypeEnum[keyof typeof CreateCloudRelayConnectionResponseDtoTypeEnum];
export const CreateCloudRelayConnectionResponseDtoDeliveryModeEnum = {
    Direct: 'direct',
    RelayQueue: 'relay-queue',
    PlatformQueue: 'platform-queue',
    Hybrid: 'hybrid'
} as const;

export type CreateCloudRelayConnectionResponseDtoDeliveryModeEnum = typeof CreateCloudRelayConnectionResponseDtoDeliveryModeEnum[keyof typeof CreateCloudRelayConnectionResponseDtoDeliveryModeEnum];
export const CreateCloudRelayConnectionResponseDtoSqsQueueModeEnum = {
    Platform: 'platform',
    Relay: 'relay'
} as const;

export type CreateCloudRelayConnectionResponseDtoSqsQueueModeEnum = typeof CreateCloudRelayConnectionResponseDtoSqsQueueModeEnum[keyof typeof CreateCloudRelayConnectionResponseDtoSqsQueueModeEnum];


