/* tslint:disable */
/* eslint-disable */
/**
 * Derrops API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateRelayInstanceDto {
    /**
     * Human-readable name for this relay instance
     */
    'name': string;
    /**
     * Base URL of the relay (must be HTTPS)
     */
    'url': string;
}

