/* tslint:disable */
/* eslint-disable */
/**
 * Derrops API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateApiDto {
    'name': string;
    'description'?: string;
    'externalUrl'?: string;
    'versionStrategy'?: CreateApiDtoVersionStrategyEnum;
    /**
     * Cron schedule for url_fetch strategy (UTC). Uses platform default when omitted.
     */
    'fetchCron'?: string;
    /**
     * URL to fetch the spec from (url_fetch strategy only)
     */
    'fetchUrl'?: string;
}

export const CreateApiDtoVersionStrategyEnum = {
    Manual: 'manual',
    UrlFetch: 'url_fetch'
} as const;

export type CreateApiDtoVersionStrategyEnum = typeof CreateApiDtoVersionStrategyEnum[keyof typeof CreateApiDtoVersionStrategyEnum];


