/* tslint:disable */
/* eslint-disable */
/**
 * Derrops API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface OaSpecRef {
    /**
     * S3 bucket where the raw spec is stored
     */
    'bucket'?: string;
    /**
     * S3 object key — {tenantId}/APIs/{provider}/{service}/{version}/openapi.yaml
     */
    'key'?: string;
    /**
     * Latest indexed spec version string (e.g. \"3.1.0\")
     */
    'latestVersion'?: string;
    /**
     * OpenSearch document ID of the latest spec in the global catalogue index
     */
    'globalOpensearchId'?: string;
    /**
     * Number of operations in the latest indexed spec
     */
    'operationCount'?: number;
    /**
     * Number of servers in the latest indexed spec
     */
    'serverCount'?: number;
    /**
     * Number of unique parameters in the latest indexed spec
     */
    'parameterCount'?: number;
    /**
     * Number of schema models in the latest indexed spec
     */
    'modelCount'?: number;
    /**
     * Timestamp of the last successful indexing run
     */
    'lastIndexedAt'?: string;
}

