/* tslint:disable */
/* eslint-disable */
/**
 * Derrops API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AggregationBucket } from './aggregation-bucket';

export interface SearchAggregations {
    /**
     * Provider aggregations
     */
    'providers': Array<AggregationBucket>;
    /**
     * Tag aggregations
     */
    'tags': Array<AggregationBucket>;
    /**
     * HTTP method aggregations
     */
    'methods': Array<AggregationBucket>;
    /**
     * Path prefix aggregations
     */
    'pathPrefixes': Array<AggregationBucket>;
}

