/* tslint:disable */
/* eslint-disable */
/**
 * Derrops API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateCloudRelayConnectionDto {
    /**
     * New human-readable name for the connection.
     */
    'name'?: string;
    /**
     * Updated base URL of the relay. Not applicable for platform-queue connections (no inbound URL).
     */
    'url'?: string;
    /**
     * UUID of an AegisInstance to link. Must belong to the same tenant. Pass null to unlink the current Aegis.
     */
    'aegis_id'?: string | null;
}

