/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdoptApiDto } from '../models';
// @ts-ignore
import type { ApiEntity } from '../models';
// @ts-ignore
import type { CreateApiDto } from '../models';
// @ts-ignore
import type { OpenApiInfoResultDto } from '../models';
// @ts-ignore
import type { UpdateApiDto } from '../models';
/**
 * APIApi - axios parameter creator
 */
export const APIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates an api row with management_mode=platform pointing to the specified global catalogue document. No private index is provisioned — the tenant reads from the platform-managed global tier.
         * @summary Adopt a platform-managed API from the global catalogue
         * @param {AdoptApiDto} adoptApiDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerAdopt: async (adoptApiDto: AdoptApiDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'adoptApiDto' is not null or undefined
            assertParamExists('apiControllerAdopt', 'adoptApiDto', adoptApiDto)
            const localVarPath = `/apis/adopt`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adoptApiDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new API
         * @param {CreateApiDto} createApiDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerCreate: async (createApiDto: CreateApiDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createApiDto' is not null or undefined
            assertParamExists('apiControllerCreate', 'createApiDto', createApiDto)
            const localVarPath = `/apis`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createApiDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List the tenant\'s APIs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/apis`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single API
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiControllerFindOne', 'id', id)
            const localVarPath = `/apis/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Downloads the YAML/JSON at openapi_doc_url (server-side, bypassing browser CORS restrictions) and returns the info.title, info.description, and info.version fields.
         * @summary Fetch the info block from a remote OpenAPI document
         * @param {string} openapiDocUrl URL of the remote OpenAPI document
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerGetInfo: async (openapiDocUrl: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'openapiDocUrl' is not null or undefined
            assertParamExists('apiControllerGetInfo', 'openapiDocUrl', openapiDocUrl)
            const localVarPath = `/apis/info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (openapiDocUrl !== undefined) {
                localVarQueryParameter['openapi_doc_url'] = openapiDocUrl;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete an API
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiControllerRemove', 'id', id)
            const localVarPath = `/apis/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an API (name, description, externalUrl, fetch strategy)
         * @param {string} id 
         * @param {UpdateApiDto} updateApiDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerUpdate: async (id: string, updateApiDto: UpdateApiDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiControllerUpdate', 'id', id)
            // verify required parameter 'updateApiDto' is not null or undefined
            assertParamExists('apiControllerUpdate', 'updateApiDto', updateApiDto)
            const localVarPath = `/apis/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateApiDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * APIApi - functional programming interface
 */
export const APIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = APIApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates an api row with management_mode=platform pointing to the specified global catalogue document. No private index is provisioned — the tenant reads from the platform-managed global tier.
         * @summary Adopt a platform-managed API from the global catalogue
         * @param {AdoptApiDto} adoptApiDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiControllerAdopt(adoptApiDto: AdoptApiDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiControllerAdopt(adoptApiDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIApi.apiControllerAdopt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new API
         * @param {CreateApiDto} createApiDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiControllerCreate(createApiDto: CreateApiDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiControllerCreate(createApiDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIApi.apiControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List the tenant\'s APIs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ApiEntity>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIApi.apiControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single API
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIApi.apiControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Downloads the YAML/JSON at openapi_doc_url (server-side, bypassing browser CORS restrictions) and returns the info.title, info.description, and info.version fields.
         * @summary Fetch the info block from a remote OpenAPI document
         * @param {string} openapiDocUrl URL of the remote OpenAPI document
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiControllerGetInfo(openapiDocUrl: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OpenApiInfoResultDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiControllerGetInfo(openapiDocUrl, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIApi.apiControllerGetInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete an API
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIApi.apiControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an API (name, description, externalUrl, fetch strategy)
         * @param {string} id 
         * @param {UpdateApiDto} updateApiDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiControllerUpdate(id: string, updateApiDto: UpdateApiDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiControllerUpdate(id, updateApiDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIApi.apiControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * APIApi - factory interface
 */
export const APIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = APIApiFp(configuration)
    return {
        /**
         * Creates an api row with management_mode=platform pointing to the specified global catalogue document. No private index is provisioned — the tenant reads from the platform-managed global tier.
         * @summary Adopt a platform-managed API from the global catalogue
         * @param {AdoptApiDto} adoptApiDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerAdopt(adoptApiDto: AdoptApiDto, options?: RawAxiosRequestConfig): AxiosPromise<ApiEntity> {
            return localVarFp.apiControllerAdopt(adoptApiDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new API
         * @param {CreateApiDto} createApiDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerCreate(createApiDto: CreateApiDto, options?: RawAxiosRequestConfig): AxiosPromise<ApiEntity> {
            return localVarFp.apiControllerCreate(createApiDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List the tenant\'s APIs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<ApiEntity>> {
            return localVarFp.apiControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single API
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiEntity> {
            return localVarFp.apiControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Downloads the YAML/JSON at openapi_doc_url (server-side, bypassing browser CORS restrictions) and returns the info.title, info.description, and info.version fields.
         * @summary Fetch the info block from a remote OpenAPI document
         * @param {string} openapiDocUrl URL of the remote OpenAPI document
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerGetInfo(openapiDocUrl: string, options?: RawAxiosRequestConfig): AxiosPromise<OpenApiInfoResultDto> {
            return localVarFp.apiControllerGetInfo(openapiDocUrl, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete an API
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerRemove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an API (name, description, externalUrl, fetch strategy)
         * @param {string} id 
         * @param {UpdateApiDto} updateApiDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiControllerUpdate(id: string, updateApiDto: UpdateApiDto, options?: RawAxiosRequestConfig): AxiosPromise<ApiEntity> {
            return localVarFp.apiControllerUpdate(id, updateApiDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * APIApi - object-oriented interface
 */
export class APIApi extends BaseAPI {
    /**
     * Creates an api row with management_mode=platform pointing to the specified global catalogue document. No private index is provisioned — the tenant reads from the platform-managed global tier.
     * @summary Adopt a platform-managed API from the global catalogue
     * @param {AdoptApiDto} adoptApiDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiControllerAdopt(adoptApiDto: AdoptApiDto, options?: RawAxiosRequestConfig) {
        return APIApiFp(this.configuration).apiControllerAdopt(adoptApiDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new API
     * @param {CreateApiDto} createApiDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiControllerCreate(createApiDto: CreateApiDto, options?: RawAxiosRequestConfig) {
        return APIApiFp(this.configuration).apiControllerCreate(createApiDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List the tenant\'s APIs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiControllerFindAll(options?: RawAxiosRequestConfig) {
        return APIApiFp(this.configuration).apiControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single API
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return APIApiFp(this.configuration).apiControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Downloads the YAML/JSON at openapi_doc_url (server-side, bypassing browser CORS restrictions) and returns the info.title, info.description, and info.version fields.
     * @summary Fetch the info block from a remote OpenAPI document
     * @param {string} openapiDocUrl URL of the remote OpenAPI document
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiControllerGetInfo(openapiDocUrl: string, options?: RawAxiosRequestConfig) {
        return APIApiFp(this.configuration).apiControllerGetInfo(openapiDocUrl, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete an API
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiControllerRemove(id: string, options?: RawAxiosRequestConfig) {
        return APIApiFp(this.configuration).apiControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an API (name, description, externalUrl, fetch strategy)
     * @param {string} id 
     * @param {UpdateApiDto} updateApiDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiControllerUpdate(id: string, updateApiDto: UpdateApiDto, options?: RawAxiosRequestConfig) {
        return APIApiFp(this.configuration).apiControllerUpdate(id, updateApiDto, options).then((request) => request(this.axios, this.basePath));
    }
}

