/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
import type { Configuration } from '../configuration'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setBearerAuthToObject,
  setSearchParams,
  toPathString,
} from '../common'
// @ts-ignore
import { BASE_PATH, BaseAPI, RequiredError, operationServerMap, type RequestArgs } from '../base'
/**
 * OpenAPIIndexerApi - axios parameter creator
 */
export const OpenAPIIndexerApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Paginated models for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetModelsOrderEnum} [order]
     * @param {string} [q]
     * @param {string} [usedIn] request | response
     * @param {string} [operationId]
     * @param {string} [sort]
     * @param {any} [version]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetModels: async (
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetModelsOrderEnum,
      q?: string,
      usedIn?: string,
      operationId?: string,
      sort?: string,
      version?: any,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiId' is not null or undefined
      assertParamExists('openApiIndexerControllerGetModels', 'apiId', apiId)
      const localVarPath = `/openapi/api/{apiId}/models`.replace(
        `{${'apiId'}}`,
        encodeURIComponent(String(apiId)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (from !== undefined) {
        localVarQueryParameter['from'] = from
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      if (order !== undefined) {
        localVarQueryParameter['order'] = order
      }

      if (q !== undefined) {
        localVarQueryParameter['q'] = q
      }

      if (usedIn !== undefined) {
        localVarQueryParameter['usedIn'] = usedIn
      }

      if (operationId !== undefined) {
        localVarQueryParameter['operationId'] = operationId
      }

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort
      }

      if (version !== undefined) {
        for (const [key, value] of Object.entries(version)) {
          localVarQueryParameter[key] = value
        }
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Paginated operations for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetOperationsOrderEnum} [order]
     * @param {string} [q] Free-text search
     * @param {string} [method] Comma-separated HTTP method filter
     * @param {string} [tag] Tag filter
     * @param {string} [sort]
     * @param {any} [version] Specific version or \&quot;latest\&quot; (default)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetOperations: async (
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetOperationsOrderEnum,
      q?: string,
      method?: string,
      tag?: string,
      sort?: string,
      version?: any,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiId' is not null or undefined
      assertParamExists('openApiIndexerControllerGetOperations', 'apiId', apiId)
      const localVarPath = `/openapi/api/{apiId}/operations`.replace(
        `{${'apiId'}}`,
        encodeURIComponent(String(apiId)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (from !== undefined) {
        localVarQueryParameter['from'] = from
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      if (order !== undefined) {
        localVarQueryParameter['order'] = order
      }

      if (q !== undefined) {
        localVarQueryParameter['q'] = q
      }

      if (method !== undefined) {
        localVarQueryParameter['method'] = method
      }

      if (tag !== undefined) {
        localVarQueryParameter['tag'] = tag
      }

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort
      }

      if (version !== undefined) {
        for (const [key, value] of Object.entries(version)) {
          localVarQueryParameter[key] = value
        }
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Paginated parameters for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetParametersOrderEnum} [order]
     * @param {string} [q]
     * @param {string} [location] path | query | header | cookie
     * @param {string} [operationId]
     * @param {string} [sort]
     * @param {any} [version]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetParameters: async (
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetParametersOrderEnum,
      q?: string,
      location?: string,
      operationId?: string,
      sort?: string,
      version?: any,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiId' is not null or undefined
      assertParamExists('openApiIndexerControllerGetParameters', 'apiId', apiId)
      const localVarPath = `/openapi/api/{apiId}/parameters`.replace(
        `{${'apiId'}}`,
        encodeURIComponent(String(apiId)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (from !== undefined) {
        localVarQueryParameter['from'] = from
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      if (order !== undefined) {
        localVarQueryParameter['order'] = order
      }

      if (q !== undefined) {
        localVarQueryParameter['q'] = q
      }

      if (location !== undefined) {
        localVarQueryParameter['location'] = location
      }

      if (operationId !== undefined) {
        localVarQueryParameter['operationId'] = operationId
      }

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort
      }

      if (version !== undefined) {
        for (const [key, value] of Object.entries(version)) {
          localVarQueryParameter[key] = value
        }
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Paginated servers for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetServersOrderEnum} [order]
     * @param {string} [sort]
     * @param {any} [version]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetServers: async (
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetServersOrderEnum,
      sort?: string,
      version?: any,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiId' is not null or undefined
      assertParamExists('openApiIndexerControllerGetServers', 'apiId', apiId)
      const localVarPath = `/openapi/api/{apiId}/servers`.replace(
        `{${'apiId'}}`,
        encodeURIComponent(String(apiId)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (from !== undefined) {
        localVarQueryParameter['from'] = from
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      if (order !== undefined) {
        localVarQueryParameter['order'] = order
      }

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort
      }

      if (version !== undefined) {
        for (const [key, value] of Object.entries(version)) {
          localVarQueryParameter[key] = value
        }
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Get a pre-signed PUT URL for uploading a spec to the OASpec bucket
     * @param {object} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetUploadUrl: async (
      body: object,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'body' is not null or undefined
      assertParamExists('openApiIndexerControllerGetUploadUrl', 'body', body)
      const localVarPath = `/openapi/upload-url`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        body,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Paginated spec version history for an API
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetVersionsOrderEnum} [order]
     * @param {string} [sort]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetVersions: async (
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetVersionsOrderEnum,
      sort?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiId' is not null or undefined
      assertParamExists('openApiIndexerControllerGetVersions', 'apiId', apiId)
      const localVarPath = `/openapi/api/{apiId}/versions`.replace(
        `{${'apiId'}}`,
        encodeURIComponent(String(apiId)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (from !== undefined) {
        localVarQueryParameter['from'] = from
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      if (order !== undefined) {
        localVarQueryParameter['order'] = order
      }

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Index a spec from S3 — runs the 6-step OASpec pipeline
     * @param {object} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerIndexFromS3: async (
      body: object,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'body' is not null or undefined
      assertParamExists('openApiIndexerControllerIndexFromS3', 'body', body)
      const localVarPath = `/openapi/index`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        body,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Search the platform-managed API catalogue
     * @param {number} [offset] Offset (default 0)
     * @param {number} [limit] Max results (default 10)
     * @param {any} [q] Search query
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerSearchCatalogue: async (
      offset?: number,
      limit?: number,
      q?: any,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/openapi/catalogue`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (offset !== undefined) {
        localVarQueryParameter['offset'] = offset
      }

      if (limit !== undefined) {
        localVarQueryParameter['limit'] = limit
      }

      if (q !== undefined) {
        for (const [key, value] of Object.entries(q)) {
          localVarQueryParameter[key] = value
        }
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * OpenAPIIndexerApi - functional programming interface
 */
export const OpenAPIIndexerApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = OpenAPIIndexerApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @summary Paginated models for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetModelsOrderEnum} [order]
     * @param {string} [q]
     * @param {string} [usedIn] request | response
     * @param {string} [operationId]
     * @param {string} [sort]
     * @param {any} [version]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async openApiIndexerControllerGetModels(
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetModelsOrderEnum,
      q?: string,
      usedIn?: string,
      operationId?: string,
      sort?: string,
      version?: any,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.openApiIndexerControllerGetModels(
        apiId,
        from,
        size,
        order,
        q,
        usedIn,
        operationId,
        sort,
        version,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerGetModels']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Paginated operations for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetOperationsOrderEnum} [order]
     * @param {string} [q] Free-text search
     * @param {string} [method] Comma-separated HTTP method filter
     * @param {string} [tag] Tag filter
     * @param {string} [sort]
     * @param {any} [version] Specific version or \&quot;latest\&quot; (default)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async openApiIndexerControllerGetOperations(
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetOperationsOrderEnum,
      q?: string,
      method?: string,
      tag?: string,
      sort?: string,
      version?: any,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.openApiIndexerControllerGetOperations(
          apiId,
          from,
          size,
          order,
          q,
          method,
          tag,
          sort,
          version,
          options,
        )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerGetOperations']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Paginated parameters for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetParametersOrderEnum} [order]
     * @param {string} [q]
     * @param {string} [location] path | query | header | cookie
     * @param {string} [operationId]
     * @param {string} [sort]
     * @param {any} [version]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async openApiIndexerControllerGetParameters(
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetParametersOrderEnum,
      q?: string,
      location?: string,
      operationId?: string,
      sort?: string,
      version?: any,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.openApiIndexerControllerGetParameters(
          apiId,
          from,
          size,
          order,
          q,
          location,
          operationId,
          sort,
          version,
          options,
        )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerGetParameters']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Paginated servers for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetServersOrderEnum} [order]
     * @param {string} [sort]
     * @param {any} [version]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async openApiIndexerControllerGetServers(
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetServersOrderEnum,
      sort?: string,
      version?: any,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.openApiIndexerControllerGetServers(
        apiId,
        from,
        size,
        order,
        sort,
        version,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerGetServers']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Get a pre-signed PUT URL for uploading a spec to the OASpec bucket
     * @param {object} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async openApiIndexerControllerGetUploadUrl(
      body: object,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.openApiIndexerControllerGetUploadUrl(body, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerGetUploadUrl']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Paginated spec version history for an API
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetVersionsOrderEnum} [order]
     * @param {string} [sort]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async openApiIndexerControllerGetVersions(
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetVersionsOrderEnum,
      sort?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.openApiIndexerControllerGetVersions(
        apiId,
        from,
        size,
        order,
        sort,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerGetVersions']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Index a spec from S3 — runs the 6-step OASpec pipeline
     * @param {object} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async openApiIndexerControllerIndexFromS3(
      body: object,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.openApiIndexerControllerIndexFromS3(
        body,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerIndexFromS3']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Search the platform-managed API catalogue
     * @param {number} [offset] Offset (default 0)
     * @param {number} [limit] Max results (default 10)
     * @param {any} [q] Search query
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async openApiIndexerControllerSearchCatalogue(
      offset?: number,
      limit?: number,
      q?: any,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.openApiIndexerControllerSearchCatalogue(
          offset,
          limit,
          q,
          options,
        )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerSearchCatalogue']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * OpenAPIIndexerApi - factory interface
 */
export const OpenAPIIndexerApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = OpenAPIIndexerApiFp(configuration)
  return {
    /**
     *
     * @summary Paginated models for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetModelsOrderEnum} [order]
     * @param {string} [q]
     * @param {string} [usedIn] request | response
     * @param {string} [operationId]
     * @param {string} [sort]
     * @param {any} [version]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetModels(
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetModelsOrderEnum,
      q?: string,
      usedIn?: string,
      operationId?: string,
      sort?: string,
      version?: any,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .openApiIndexerControllerGetModels(
          apiId,
          from,
          size,
          order,
          q,
          usedIn,
          operationId,
          sort,
          version,
          options,
        )
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Paginated operations for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetOperationsOrderEnum} [order]
     * @param {string} [q] Free-text search
     * @param {string} [method] Comma-separated HTTP method filter
     * @param {string} [tag] Tag filter
     * @param {string} [sort]
     * @param {any} [version] Specific version or \&quot;latest\&quot; (default)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetOperations(
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetOperationsOrderEnum,
      q?: string,
      method?: string,
      tag?: string,
      sort?: string,
      version?: any,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .openApiIndexerControllerGetOperations(
          apiId,
          from,
          size,
          order,
          q,
          method,
          tag,
          sort,
          version,
          options,
        )
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Paginated parameters for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetParametersOrderEnum} [order]
     * @param {string} [q]
     * @param {string} [location] path | query | header | cookie
     * @param {string} [operationId]
     * @param {string} [sort]
     * @param {any} [version]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetParameters(
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetParametersOrderEnum,
      q?: string,
      location?: string,
      operationId?: string,
      sort?: string,
      version?: any,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .openApiIndexerControllerGetParameters(
          apiId,
          from,
          size,
          order,
          q,
          location,
          operationId,
          sort,
          version,
          options,
        )
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Paginated servers for an API version
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetServersOrderEnum} [order]
     * @param {string} [sort]
     * @param {any} [version]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetServers(
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetServersOrderEnum,
      sort?: string,
      version?: any,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .openApiIndexerControllerGetServers(apiId, from, size, order, sort, version, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Get a pre-signed PUT URL for uploading a spec to the OASpec bucket
     * @param {object} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetUploadUrl(
      body: object,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .openApiIndexerControllerGetUploadUrl(body, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Paginated spec version history for an API
     * @param {string} apiId API UUID
     * @param {number} [from]
     * @param {number} [size]
     * @param {OpenApiIndexerControllerGetVersionsOrderEnum} [order]
     * @param {string} [sort]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerGetVersions(
      apiId: string,
      from?: number,
      size?: number,
      order?: OpenApiIndexerControllerGetVersionsOrderEnum,
      sort?: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .openApiIndexerControllerGetVersions(apiId, from, size, order, sort, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Index a spec from S3 — runs the 6-step OASpec pipeline
     * @param {object} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerIndexFromS3(
      body: object,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .openApiIndexerControllerIndexFromS3(body, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Search the platform-managed API catalogue
     * @param {number} [offset] Offset (default 0)
     * @param {number} [limit] Max results (default 10)
     * @param {any} [q] Search query
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    openApiIndexerControllerSearchCatalogue(
      offset?: number,
      limit?: number,
      q?: any,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .openApiIndexerControllerSearchCatalogue(offset, limit, q, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * OpenAPIIndexerApi - object-oriented interface
 */
export class OpenAPIIndexerApi extends BaseAPI {
  /**
   *
   * @summary Paginated models for an API version
   * @param {string} apiId API UUID
   * @param {number} [from]
   * @param {number} [size]
   * @param {OpenApiIndexerControllerGetModelsOrderEnum} [order]
   * @param {string} [q]
   * @param {string} [usedIn] request | response
   * @param {string} [operationId]
   * @param {string} [sort]
   * @param {any} [version]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public openApiIndexerControllerGetModels(
    apiId: string,
    from?: number,
    size?: number,
    order?: OpenApiIndexerControllerGetModelsOrderEnum,
    q?: string,
    usedIn?: string,
    operationId?: string,
    sort?: string,
    version?: any,
    options?: RawAxiosRequestConfig,
  ) {
    return OpenAPIIndexerApiFp(this.configuration)
      .openApiIndexerControllerGetModels(
        apiId,
        from,
        size,
        order,
        q,
        usedIn,
        operationId,
        sort,
        version,
        options,
      )
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Paginated operations for an API version
   * @param {string} apiId API UUID
   * @param {number} [from]
   * @param {number} [size]
   * @param {OpenApiIndexerControllerGetOperationsOrderEnum} [order]
   * @param {string} [q] Free-text search
   * @param {string} [method] Comma-separated HTTP method filter
   * @param {string} [tag] Tag filter
   * @param {string} [sort]
   * @param {any} [version] Specific version or \&quot;latest\&quot; (default)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public openApiIndexerControllerGetOperations(
    apiId: string,
    from?: number,
    size?: number,
    order?: OpenApiIndexerControllerGetOperationsOrderEnum,
    q?: string,
    method?: string,
    tag?: string,
    sort?: string,
    version?: any,
    options?: RawAxiosRequestConfig,
  ) {
    return OpenAPIIndexerApiFp(this.configuration)
      .openApiIndexerControllerGetOperations(
        apiId,
        from,
        size,
        order,
        q,
        method,
        tag,
        sort,
        version,
        options,
      )
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Paginated parameters for an API version
   * @param {string} apiId API UUID
   * @param {number} [from]
   * @param {number} [size]
   * @param {OpenApiIndexerControllerGetParametersOrderEnum} [order]
   * @param {string} [q]
   * @param {string} [location] path | query | header | cookie
   * @param {string} [operationId]
   * @param {string} [sort]
   * @param {any} [version]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public openApiIndexerControllerGetParameters(
    apiId: string,
    from?: number,
    size?: number,
    order?: OpenApiIndexerControllerGetParametersOrderEnum,
    q?: string,
    location?: string,
    operationId?: string,
    sort?: string,
    version?: any,
    options?: RawAxiosRequestConfig,
  ) {
    return OpenAPIIndexerApiFp(this.configuration)
      .openApiIndexerControllerGetParameters(
        apiId,
        from,
        size,
        order,
        q,
        location,
        operationId,
        sort,
        version,
        options,
      )
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Paginated servers for an API version
   * @param {string} apiId API UUID
   * @param {number} [from]
   * @param {number} [size]
   * @param {OpenApiIndexerControllerGetServersOrderEnum} [order]
   * @param {string} [sort]
   * @param {any} [version]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public openApiIndexerControllerGetServers(
    apiId: string,
    from?: number,
    size?: number,
    order?: OpenApiIndexerControllerGetServersOrderEnum,
    sort?: string,
    version?: any,
    options?: RawAxiosRequestConfig,
  ) {
    return OpenAPIIndexerApiFp(this.configuration)
      .openApiIndexerControllerGetServers(apiId, from, size, order, sort, version, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Get a pre-signed PUT URL for uploading a spec to the OASpec bucket
   * @param {object} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public openApiIndexerControllerGetUploadUrl(body: object, options?: RawAxiosRequestConfig) {
    return OpenAPIIndexerApiFp(this.configuration)
      .openApiIndexerControllerGetUploadUrl(body, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Paginated spec version history for an API
   * @param {string} apiId API UUID
   * @param {number} [from]
   * @param {number} [size]
   * @param {OpenApiIndexerControllerGetVersionsOrderEnum} [order]
   * @param {string} [sort]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public openApiIndexerControllerGetVersions(
    apiId: string,
    from?: number,
    size?: number,
    order?: OpenApiIndexerControllerGetVersionsOrderEnum,
    sort?: string,
    options?: RawAxiosRequestConfig,
  ) {
    return OpenAPIIndexerApiFp(this.configuration)
      .openApiIndexerControllerGetVersions(apiId, from, size, order, sort, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Index a spec from S3 — runs the 6-step OASpec pipeline
   * @param {object} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public openApiIndexerControllerIndexFromS3(body: object, options?: RawAxiosRequestConfig) {
    return OpenAPIIndexerApiFp(this.configuration)
      .openApiIndexerControllerIndexFromS3(body, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Search the platform-managed API catalogue
   * @param {number} [offset] Offset (default 0)
   * @param {number} [limit] Max results (default 10)
   * @param {any} [q] Search query
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public openApiIndexerControllerSearchCatalogue(
    offset?: number,
    limit?: number,
    q?: any,
    options?: RawAxiosRequestConfig,
  ) {
    return OpenAPIIndexerApiFp(this.configuration)
      .openApiIndexerControllerSearchCatalogue(offset, limit, q, options)
      .then((request) => request(this.axios, this.basePath))
  }
}

export const OpenApiIndexerControllerGetModelsOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const
export type OpenApiIndexerControllerGetModelsOrderEnum =
  (typeof OpenApiIndexerControllerGetModelsOrderEnum)[keyof typeof OpenApiIndexerControllerGetModelsOrderEnum]
export const OpenApiIndexerControllerGetOperationsOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const
export type OpenApiIndexerControllerGetOperationsOrderEnum =
  (typeof OpenApiIndexerControllerGetOperationsOrderEnum)[keyof typeof OpenApiIndexerControllerGetOperationsOrderEnum]
export const OpenApiIndexerControllerGetParametersOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const
export type OpenApiIndexerControllerGetParametersOrderEnum =
  (typeof OpenApiIndexerControllerGetParametersOrderEnum)[keyof typeof OpenApiIndexerControllerGetParametersOrderEnum]
export const OpenApiIndexerControllerGetServersOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const
export type OpenApiIndexerControllerGetServersOrderEnum =
  (typeof OpenApiIndexerControllerGetServersOrderEnum)[keyof typeof OpenApiIndexerControllerGetServersOrderEnum]
export const OpenApiIndexerControllerGetVersionsOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const
export type OpenApiIndexerControllerGetVersionsOrderEnum =
  (typeof OpenApiIndexerControllerGetVersionsOrderEnum)[keyof typeof OpenApiIndexerControllerGetVersionsOrderEnum]
