/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * OpenAPIIndexerApi - axios parameter creator
 */
export const OpenAPIIndexerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a pre-signed PUT URL for uploading a spec to the OASpec bucket
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiIndexerControllerGetUploadUrl: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('openApiIndexerControllerGetUploadUrl', 'body', body)
            const localVarPath = `/openapi/upload-url`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Index a spec from S3 — runs the 6-step OASpec pipeline
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiIndexerControllerIndexFromS3: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('openApiIndexerControllerIndexFromS3', 'body', body)
            const localVarPath = `/openapi/index`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search the platform-managed API catalogue
         * @param {number} [offset] Offset (default 0)
         * @param {number} [limit] Max results (default 10)
         * @param {any} [q] Search query
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiIndexerControllerSearchCatalogue: async (offset?: number, limit?: number, q?: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/openapi/catalogue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (q !== undefined) {
                for (const [key, value] of Object.entries(q)) {
                    localVarQueryParameter[key] = value;
                }
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OpenAPIIndexerApi - functional programming interface
 */
export const OpenAPIIndexerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OpenAPIIndexerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get a pre-signed PUT URL for uploading a spec to the OASpec bucket
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openApiIndexerControllerGetUploadUrl(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openApiIndexerControllerGetUploadUrl(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerGetUploadUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Index a spec from S3 — runs the 6-step OASpec pipeline
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openApiIndexerControllerIndexFromS3(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openApiIndexerControllerIndexFromS3(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerIndexFromS3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search the platform-managed API catalogue
         * @param {number} [offset] Offset (default 0)
         * @param {number} [limit] Max results (default 10)
         * @param {any} [q] Search query
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openApiIndexerControllerSearchCatalogue(offset?: number, limit?: number, q?: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openApiIndexerControllerSearchCatalogue(offset, limit, q, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAPIIndexerApi.openApiIndexerControllerSearchCatalogue']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OpenAPIIndexerApi - factory interface
 */
export const OpenAPIIndexerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OpenAPIIndexerApiFp(configuration)
    return {
        /**
         * 
         * @summary Get a pre-signed PUT URL for uploading a spec to the OASpec bucket
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiIndexerControllerGetUploadUrl(body: object, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.openApiIndexerControllerGetUploadUrl(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Index a spec from S3 — runs the 6-step OASpec pipeline
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiIndexerControllerIndexFromS3(body: object, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.openApiIndexerControllerIndexFromS3(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search the platform-managed API catalogue
         * @param {number} [offset] Offset (default 0)
         * @param {number} [limit] Max results (default 10)
         * @param {any} [q] Search query
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openApiIndexerControllerSearchCatalogue(offset?: number, limit?: number, q?: any, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.openApiIndexerControllerSearchCatalogue(offset, limit, q, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OpenAPIIndexerApi - object-oriented interface
 */
export class OpenAPIIndexerApi extends BaseAPI {
    /**
     * 
     * @summary Get a pre-signed PUT URL for uploading a spec to the OASpec bucket
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public openApiIndexerControllerGetUploadUrl(body: object, options?: RawAxiosRequestConfig) {
        return OpenAPIIndexerApiFp(this.configuration).openApiIndexerControllerGetUploadUrl(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Index a spec from S3 — runs the 6-step OASpec pipeline
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public openApiIndexerControllerIndexFromS3(body: object, options?: RawAxiosRequestConfig) {
        return OpenAPIIndexerApiFp(this.configuration).openApiIndexerControllerIndexFromS3(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search the platform-managed API catalogue
     * @param {number} [offset] Offset (default 0)
     * @param {number} [limit] Max results (default 10)
     * @param {any} [q] Search query
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public openApiIndexerControllerSearchCatalogue(offset?: number, limit?: number, q?: any, options?: RawAxiosRequestConfig) {
        return OpenAPIIndexerApiFp(this.configuration).openApiIndexerControllerSearchCatalogue(offset, limit, q, options).then((request) => request(this.axios, this.basePath));
    }
}

