/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateRelayInstanceDto } from '../models';
// @ts-ignore
import type { RelayInstance } from '../models';
// @ts-ignore
import type { UpdateRelayInstanceDto } from '../models';
/**
 * RelayInstanceApi - axios parameter creator
 */
export const RelayInstanceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Register a new relay instance
         * @param {CreateRelayInstanceDto} createRelayInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerCreate: async (createRelayInstanceDto: CreateRelayInstanceDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createRelayInstanceDto' is not null or undefined
            assertParamExists('relayInstanceControllerCreate', 'createRelayInstanceDto', createRelayInstanceDto)
            const localVarPath = `/cloud-relay/relay-instance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createRelayInstanceDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all relay instances for the tenant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cloud-relay/relay-instance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a relay instance by ID
         * @param {string} id RelayInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('relayInstanceControllerFindOne', 'id', id)
            const localVarPath = `/cloud-relay/relay-instance/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Trigger a health check on the relay instance (mints a platform JWT and calls relay /health)
         * @param {string} id RelayInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerHealthCheck: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('relayInstanceControllerHealthCheck', 'id', id)
            const localVarPath = `/cloud-relay/relay-instance/{id}/health-check`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a relay instance
         * @param {string} id RelayInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('relayInstanceControllerRemove', 'id', id)
            const localVarPath = `/cloud-relay/relay-instance/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a relay instance
         * @param {string} id RelayInstance UUID
         * @param {UpdateRelayInstanceDto} updateRelayInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerUpdate: async (id: string, updateRelayInstanceDto: UpdateRelayInstanceDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('relayInstanceControllerUpdate', 'id', id)
            // verify required parameter 'updateRelayInstanceDto' is not null or undefined
            assertParamExists('relayInstanceControllerUpdate', 'updateRelayInstanceDto', updateRelayInstanceDto)
            const localVarPath = `/cloud-relay/relay-instance/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateRelayInstanceDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RelayInstanceApi - functional programming interface
 */
export const RelayInstanceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RelayInstanceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Register a new relay instance
         * @param {CreateRelayInstanceDto} createRelayInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async relayInstanceControllerCreate(createRelayInstanceDto: CreateRelayInstanceDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RelayInstance>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.relayInstanceControllerCreate(createRelayInstanceDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RelayInstanceApi.relayInstanceControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all relay instances for the tenant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async relayInstanceControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RelayInstance>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.relayInstanceControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RelayInstanceApi.relayInstanceControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a relay instance by ID
         * @param {string} id RelayInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async relayInstanceControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RelayInstance>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.relayInstanceControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RelayInstanceApi.relayInstanceControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Trigger a health check on the relay instance (mints a platform JWT and calls relay /health)
         * @param {string} id RelayInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async relayInstanceControllerHealthCheck(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RelayInstance>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.relayInstanceControllerHealthCheck(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RelayInstanceApi.relayInstanceControllerHealthCheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a relay instance
         * @param {string} id RelayInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async relayInstanceControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.relayInstanceControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RelayInstanceApi.relayInstanceControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a relay instance
         * @param {string} id RelayInstance UUID
         * @param {UpdateRelayInstanceDto} updateRelayInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async relayInstanceControllerUpdate(id: string, updateRelayInstanceDto: UpdateRelayInstanceDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RelayInstance>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.relayInstanceControllerUpdate(id, updateRelayInstanceDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RelayInstanceApi.relayInstanceControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RelayInstanceApi - factory interface
 */
export const RelayInstanceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RelayInstanceApiFp(configuration)
    return {
        /**
         * 
         * @summary Register a new relay instance
         * @param {CreateRelayInstanceDto} createRelayInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerCreate(createRelayInstanceDto: CreateRelayInstanceDto, options?: RawAxiosRequestConfig): AxiosPromise<RelayInstance> {
            return localVarFp.relayInstanceControllerCreate(createRelayInstanceDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all relay instances for the tenant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<RelayInstance>> {
            return localVarFp.relayInstanceControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a relay instance by ID
         * @param {string} id RelayInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<RelayInstance> {
            return localVarFp.relayInstanceControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Trigger a health check on the relay instance (mints a platform JWT and calls relay /health)
         * @param {string} id RelayInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerHealthCheck(id: string, options?: RawAxiosRequestConfig): AxiosPromise<RelayInstance> {
            return localVarFp.relayInstanceControllerHealthCheck(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a relay instance
         * @param {string} id RelayInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerRemove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.relayInstanceControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a relay instance
         * @param {string} id RelayInstance UUID
         * @param {UpdateRelayInstanceDto} updateRelayInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        relayInstanceControllerUpdate(id: string, updateRelayInstanceDto: UpdateRelayInstanceDto, options?: RawAxiosRequestConfig): AxiosPromise<RelayInstance> {
            return localVarFp.relayInstanceControllerUpdate(id, updateRelayInstanceDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RelayInstanceApi - object-oriented interface
 */
export class RelayInstanceApi extends BaseAPI {
    /**
     * 
     * @summary Register a new relay instance
     * @param {CreateRelayInstanceDto} createRelayInstanceDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public relayInstanceControllerCreate(createRelayInstanceDto: CreateRelayInstanceDto, options?: RawAxiosRequestConfig) {
        return RelayInstanceApiFp(this.configuration).relayInstanceControllerCreate(createRelayInstanceDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all relay instances for the tenant
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public relayInstanceControllerFindAll(options?: RawAxiosRequestConfig) {
        return RelayInstanceApiFp(this.configuration).relayInstanceControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a relay instance by ID
     * @param {string} id RelayInstance UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public relayInstanceControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return RelayInstanceApiFp(this.configuration).relayInstanceControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Trigger a health check on the relay instance (mints a platform JWT and calls relay /health)
     * @param {string} id RelayInstance UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public relayInstanceControllerHealthCheck(id: string, options?: RawAxiosRequestConfig) {
        return RelayInstanceApiFp(this.configuration).relayInstanceControllerHealthCheck(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a relay instance
     * @param {string} id RelayInstance UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public relayInstanceControllerRemove(id: string, options?: RawAxiosRequestConfig) {
        return RelayInstanceApiFp(this.configuration).relayInstanceControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a relay instance
     * @param {string} id RelayInstance UUID
     * @param {UpdateRelayInstanceDto} updateRelayInstanceDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public relayInstanceControllerUpdate(id: string, updateRelayInstanceDto: UpdateRelayInstanceDto, options?: RawAxiosRequestConfig) {
        return RelayInstanceApiFp(this.configuration).relayInstanceControllerUpdate(id, updateRelayInstanceDto, options).then((request) => request(this.axios, this.basePath));
    }
}

