/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AegisCreateResponseDto } from '../models';
// @ts-ignore
import type { AegisInstance } from '../models';
// @ts-ignore
import type { AegisRegisterDto } from '../models';
// @ts-ignore
import type { CreateAegisInstanceDto } from '../models';
// @ts-ignore
import type { UpdateAegisInstanceDto } from '../models';
/**
 * AegisInstanceApi - axios parameter creator
 */
export const AegisInstanceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a one-time `registrationToken`. Configure Aegis with this token so it can complete the registration handshake via POST /cloud-relay/aegis/register.
         * @summary Register a new Aegis instance
         * @param {string} xTenantId Tenant UUID
         * @param {CreateAegisInstanceDto} createAegisInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerCreate: async (xTenantId: string, createAegisInstanceDto: CreateAegisInstanceDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xTenantId' is not null or undefined
            assertParamExists('aegisInstanceControllerCreate', 'xTenantId', xTenantId)
            // verify required parameter 'createAegisInstanceDto' is not null or undefined
            assertParamExists('aegisInstanceControllerCreate', 'createAegisInstanceDto', createAegisInstanceDto)
            const localVarPath = `/cloud-relay/aegis-instance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xTenantId != null) {
                localVarHeaderParameter['x-tenant-id'] = String(xTenantId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createAegisInstanceDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all Aegis instances for the tenant
         * @param {string} xTenantId Tenant UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerFindAll: async (xTenantId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xTenantId' is not null or undefined
            assertParamExists('aegisInstanceControllerFindAll', 'xTenantId', xTenantId)
            const localVarPath = `/cloud-relay/aegis-instance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xTenantId != null) {
                localVarHeaderParameter['x-tenant-id'] = String(xTenantId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an Aegis instance by ID
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerFindOne: async (xTenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xTenantId' is not null or undefined
            assertParamExists('aegisInstanceControllerFindOne', 'xTenantId', xTenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('aegisInstanceControllerFindOne', 'id', id)
            const localVarPath = `/cloud-relay/aegis-instance/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xTenantId != null) {
                localVarHeaderParameter['x-tenant-id'] = String(xTenantId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Trigger a health check on the Aegis instance (validates JWKS endpoint)
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerHealthCheck: async (xTenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xTenantId' is not null or undefined
            assertParamExists('aegisInstanceControllerHealthCheck', 'xTenantId', xTenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('aegisInstanceControllerHealthCheck', 'id', id)
            const localVarPath = `/cloud-relay/aegis-instance/{id}/health-check`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xTenantId != null) {
                localVarHeaderParameter['x-tenant-id'] = String(xTenantId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete an Aegis instance
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerRemove: async (xTenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xTenantId' is not null or undefined
            assertParamExists('aegisInstanceControllerRemove', 'xTenantId', xTenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('aegisInstanceControllerRemove', 'id', id)
            const localVarPath = `/cloud-relay/aegis-instance/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            if (xTenantId != null) {
                localVarHeaderParameter['x-tenant-id'] = String(xTenantId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an Aegis instance
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {UpdateAegisInstanceDto} updateAegisInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerUpdate: async (xTenantId: string, id: string, updateAegisInstanceDto: UpdateAegisInstanceDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xTenantId' is not null or undefined
            assertParamExists('aegisInstanceControllerUpdate', 'xTenantId', xTenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('aegisInstanceControllerUpdate', 'id', id)
            // verify required parameter 'updateAegisInstanceDto' is not null or undefined
            assertParamExists('aegisInstanceControllerUpdate', 'updateAegisInstanceDto', updateAegisInstanceDto)
            const localVarPath = `/cloud-relay/aegis-instance/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xTenantId != null) {
                localVarHeaderParameter['x-tenant-id'] = String(xTenantId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAegisInstanceDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Aegis posts its one-time registration token and JWKS URL. On success the instance transitions from `pending` to `active` and the token is invalidated.
         * @summary Complete Aegis instance registration (called by Aegis)
         * @param {AegisRegisterDto} aegisRegisterDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisRegisterControllerRegister: async (aegisRegisterDto: AegisRegisterDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'aegisRegisterDto' is not null or undefined
            assertParamExists('aegisRegisterControllerRegister', 'aegisRegisterDto', aegisRegisterDto)
            const localVarPath = `/cloud-relay/aegis/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(aegisRegisterDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AegisInstanceApi - functional programming interface
 */
export const AegisInstanceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AegisInstanceApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a one-time `registrationToken`. Configure Aegis with this token so it can complete the registration handshake via POST /cloud-relay/aegis/register.
         * @summary Register a new Aegis instance
         * @param {string} xTenantId Tenant UUID
         * @param {CreateAegisInstanceDto} createAegisInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aegisInstanceControllerCreate(xTenantId: string, createAegisInstanceDto: CreateAegisInstanceDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AegisCreateResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aegisInstanceControllerCreate(xTenantId, createAegisInstanceDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AegisInstanceApi.aegisInstanceControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all Aegis instances for the tenant
         * @param {string} xTenantId Tenant UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aegisInstanceControllerFindAll(xTenantId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AegisInstance>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aegisInstanceControllerFindAll(xTenantId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AegisInstanceApi.aegisInstanceControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get an Aegis instance by ID
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aegisInstanceControllerFindOne(xTenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AegisInstance>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aegisInstanceControllerFindOne(xTenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AegisInstanceApi.aegisInstanceControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Trigger a health check on the Aegis instance (validates JWKS endpoint)
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aegisInstanceControllerHealthCheck(xTenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AegisInstance>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aegisInstanceControllerHealthCheck(xTenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AegisInstanceApi.aegisInstanceControllerHealthCheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete an Aegis instance
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aegisInstanceControllerRemove(xTenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aegisInstanceControllerRemove(xTenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AegisInstanceApi.aegisInstanceControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an Aegis instance
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {UpdateAegisInstanceDto} updateAegisInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aegisInstanceControllerUpdate(xTenantId: string, id: string, updateAegisInstanceDto: UpdateAegisInstanceDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AegisInstance>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aegisInstanceControllerUpdate(xTenantId, id, updateAegisInstanceDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AegisInstanceApi.aegisInstanceControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Aegis posts its one-time registration token and JWKS URL. On success the instance transitions from `pending` to `active` and the token is invalidated.
         * @summary Complete Aegis instance registration (called by Aegis)
         * @param {AegisRegisterDto} aegisRegisterDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aegisRegisterControllerRegister(aegisRegisterDto: AegisRegisterDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AegisInstance>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aegisRegisterControllerRegister(aegisRegisterDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AegisInstanceApi.aegisRegisterControllerRegister']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AegisInstanceApi - factory interface
 */
export const AegisInstanceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AegisInstanceApiFp(configuration)
    return {
        /**
         * Returns a one-time `registrationToken`. Configure Aegis with this token so it can complete the registration handshake via POST /cloud-relay/aegis/register.
         * @summary Register a new Aegis instance
         * @param {string} xTenantId Tenant UUID
         * @param {CreateAegisInstanceDto} createAegisInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerCreate(xTenantId: string, createAegisInstanceDto: CreateAegisInstanceDto, options?: RawAxiosRequestConfig): AxiosPromise<AegisCreateResponseDto> {
            return localVarFp.aegisInstanceControllerCreate(xTenantId, createAegisInstanceDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all Aegis instances for the tenant
         * @param {string} xTenantId Tenant UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerFindAll(xTenantId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<AegisInstance>> {
            return localVarFp.aegisInstanceControllerFindAll(xTenantId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an Aegis instance by ID
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerFindOne(xTenantId: string, id: string, options?: RawAxiosRequestConfig): AxiosPromise<AegisInstance> {
            return localVarFp.aegisInstanceControllerFindOne(xTenantId, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Trigger a health check on the Aegis instance (validates JWKS endpoint)
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerHealthCheck(xTenantId: string, id: string, options?: RawAxiosRequestConfig): AxiosPromise<AegisInstance> {
            return localVarFp.aegisInstanceControllerHealthCheck(xTenantId, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete an Aegis instance
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerRemove(xTenantId: string, id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.aegisInstanceControllerRemove(xTenantId, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an Aegis instance
         * @param {string} xTenantId Tenant UUID
         * @param {string} id AegisInstance UUID
         * @param {UpdateAegisInstanceDto} updateAegisInstanceDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisInstanceControllerUpdate(xTenantId: string, id: string, updateAegisInstanceDto: UpdateAegisInstanceDto, options?: RawAxiosRequestConfig): AxiosPromise<AegisInstance> {
            return localVarFp.aegisInstanceControllerUpdate(xTenantId, id, updateAegisInstanceDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Aegis posts its one-time registration token and JWKS URL. On success the instance transitions from `pending` to `active` and the token is invalidated.
         * @summary Complete Aegis instance registration (called by Aegis)
         * @param {AegisRegisterDto} aegisRegisterDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aegisRegisterControllerRegister(aegisRegisterDto: AegisRegisterDto, options?: RawAxiosRequestConfig): AxiosPromise<AegisInstance> {
            return localVarFp.aegisRegisterControllerRegister(aegisRegisterDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AegisInstanceApi - object-oriented interface
 */
export class AegisInstanceApi extends BaseAPI {
    /**
     * Returns a one-time `registrationToken`. Configure Aegis with this token so it can complete the registration handshake via POST /cloud-relay/aegis/register.
     * @summary Register a new Aegis instance
     * @param {string} xTenantId Tenant UUID
     * @param {CreateAegisInstanceDto} createAegisInstanceDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public aegisInstanceControllerCreate(xTenantId: string, createAegisInstanceDto: CreateAegisInstanceDto, options?: RawAxiosRequestConfig) {
        return AegisInstanceApiFp(this.configuration).aegisInstanceControllerCreate(xTenantId, createAegisInstanceDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all Aegis instances for the tenant
     * @param {string} xTenantId Tenant UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public aegisInstanceControllerFindAll(xTenantId: string, options?: RawAxiosRequestConfig) {
        return AegisInstanceApiFp(this.configuration).aegisInstanceControllerFindAll(xTenantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an Aegis instance by ID
     * @param {string} xTenantId Tenant UUID
     * @param {string} id AegisInstance UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public aegisInstanceControllerFindOne(xTenantId: string, id: string, options?: RawAxiosRequestConfig) {
        return AegisInstanceApiFp(this.configuration).aegisInstanceControllerFindOne(xTenantId, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Trigger a health check on the Aegis instance (validates JWKS endpoint)
     * @param {string} xTenantId Tenant UUID
     * @param {string} id AegisInstance UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public aegisInstanceControllerHealthCheck(xTenantId: string, id: string, options?: RawAxiosRequestConfig) {
        return AegisInstanceApiFp(this.configuration).aegisInstanceControllerHealthCheck(xTenantId, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete an Aegis instance
     * @param {string} xTenantId Tenant UUID
     * @param {string} id AegisInstance UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public aegisInstanceControllerRemove(xTenantId: string, id: string, options?: RawAxiosRequestConfig) {
        return AegisInstanceApiFp(this.configuration).aegisInstanceControllerRemove(xTenantId, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an Aegis instance
     * @param {string} xTenantId Tenant UUID
     * @param {string} id AegisInstance UUID
     * @param {UpdateAegisInstanceDto} updateAegisInstanceDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public aegisInstanceControllerUpdate(xTenantId: string, id: string, updateAegisInstanceDto: UpdateAegisInstanceDto, options?: RawAxiosRequestConfig) {
        return AegisInstanceApiFp(this.configuration).aegisInstanceControllerUpdate(xTenantId, id, updateAegisInstanceDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Aegis posts its one-time registration token and JWKS URL. On success the instance transitions from `pending` to `active` and the token is invalidated.
     * @summary Complete Aegis instance registration (called by Aegis)
     * @param {AegisRegisterDto} aegisRegisterDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public aegisRegisterControllerRegister(aegisRegisterDto: AegisRegisterDto, options?: RawAxiosRequestConfig) {
        return AegisInstanceApiFp(this.configuration).aegisRegisterControllerRegister(aegisRegisterDto, options).then((request) => request(this.axios, this.basePath));
    }
}

