/* tslint:disable */
/* eslint-disable */
/**
 * SLAOps API
 * Internal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CloudRelayConnection } from '../models';
// @ts-ignore
import type { CloudRelayControllerDeleteConnection200Response } from '../models';
// @ts-ignore
import type { CloudRelayControllerGetJwks200Response } from '../models';
// @ts-ignore
import type { CloudRelayJob } from '../models';
// @ts-ignore
import type { CreateCloudRelayConnectionDto } from '../models';
// @ts-ignore
import type { CreateCloudRelayJobDto } from '../models';
/**
 * CloudRelayApi - axios parameter creator
 */
export const CloudRelayApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The relay polls this endpoint to claim jobs for legacy HTTP-polling connections. SQS-enabled relays (local-dev) receive jobs via SQS long-poll instead. Authenticate with the connection api_key as a Bearer token.
         * @summary Claim the next pending platform-queue job (called by the relay)
         * @param {string} authorization Bearer &lt;connection api_key&gt;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerClaimNextJob: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('cloudRelayControllerClaimNextJob', 'authorization', authorization)
            const localVarPath = `/cloud-relay/queue/next`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * For local-dev relays (type=local-dev), a dedicated SQS FIFO queue is provisioned automatically. The response includes sqs_queue_url and sqs_region.  tenantId and userId are read from the verified Cognito id_token — no client-supplied headers are trusted.
         * @summary Register a new relay connection
         * @param {CreateCloudRelayConnectionDto} createCloudRelayConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerCreateConnection: async (createCloudRelayConnectionDto: CreateCloudRelayConnectionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCloudRelayConnectionDto' is not null or undefined
            assertParamExists('cloudRelayControllerCreateConnection', 'createCloudRelayConnectionDto', createCloudRelayConnectionDto)
            const localVarPath = `/cloud-relay/connection`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCloudRelayConnectionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a relay connection and its SQS queue (if any)
         * @param {string} id Connection UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerDeleteConnection: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cloudRelayControllerDeleteConnection', 'id', id)
            const localVarPath = `/cloud-relay/connection/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * After executing a claimed job, the relay posts the result here. Set `failed: true` to mark the job as failed.
         * @summary Deliver the result of a platform-queue job (called by the relay)
         * @param {string} id Job UUID (from GET /cloud-relay/queue/next or SQS message body)
         * @param {string} authorization Bearer &lt;connection api_key&gt;
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerDeliverJobResult: async (id: string, authorization: string, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cloudRelayControllerDeliverJobResult', 'id', id)
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('cloudRelayControllerDeliverJobResult', 'authorization', authorization)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('cloudRelayControllerDeliverJobResult', 'body', body)
            const localVarPath = `/cloud-relay/job/{id}/result`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * slaops-cloud routes the request via the connection delivery_mode. direct: result is returned inline (completed immediately). relay-queue/platform-queue: job is pending — poll GET /cloud-relay/job/:id for the result.
         * @summary Submit a proxy job
         * @param {CreateCloudRelayJobDto} createCloudRelayJobDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerEnqueueJob: async (createCloudRelayJobDto: CreateCloudRelayJobDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCloudRelayJobDto' is not null or undefined
            assertParamExists('cloudRelayControllerEnqueueJob', 'createCloudRelayJobDto', createCloudRelayJobDto)
            const localVarPath = `/cloud-relay/job`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCloudRelayJobDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List relay connections for the authenticated user\'s tenant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerFindAllConnections: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cloud-relay/connection`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * For relay-queue mode, slaops-cloud syncs status from the relay on each poll. For platform-queue and direct modes, returns the stored job state.
         * @summary Poll for the result of a proxy job
         * @param {string} id Job UUID returned by POST /cloud-relay/job
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerGetJob: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cloudRelayControllerGetJob', 'id', id)
            const localVarPath = `/cloud-relay/job/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Vendor JWKS endpoint (used by relays and Aegis to validate platform JWTs)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerGetJwks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cloud-relay/.well-known/jwks.json`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CloudRelayApi - functional programming interface
 */
export const CloudRelayApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CloudRelayApiAxiosParamCreator(configuration)
    return {
        /**
         * The relay polls this endpoint to claim jobs for legacy HTTP-polling connections. SQS-enabled relays (local-dev) receive jobs via SQS long-poll instead. Authenticate with the connection api_key as a Bearer token.
         * @summary Claim the next pending platform-queue job (called by the relay)
         * @param {string} authorization Bearer &lt;connection api_key&gt;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudRelayControllerClaimNextJob(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudRelayJob>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudRelayControllerClaimNextJob(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudRelayApi.cloudRelayControllerClaimNextJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * For local-dev relays (type=local-dev), a dedicated SQS FIFO queue is provisioned automatically. The response includes sqs_queue_url and sqs_region.  tenantId and userId are read from the verified Cognito id_token — no client-supplied headers are trusted.
         * @summary Register a new relay connection
         * @param {CreateCloudRelayConnectionDto} createCloudRelayConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudRelayControllerCreateConnection(createCloudRelayConnectionDto: CreateCloudRelayConnectionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudRelayConnection>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudRelayControllerCreateConnection(createCloudRelayConnectionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudRelayApi.cloudRelayControllerCreateConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a relay connection and its SQS queue (if any)
         * @param {string} id Connection UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudRelayControllerDeleteConnection(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudRelayControllerDeleteConnection200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudRelayControllerDeleteConnection(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudRelayApi.cloudRelayControllerDeleteConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * After executing a claimed job, the relay posts the result here. Set `failed: true` to mark the job as failed.
         * @summary Deliver the result of a platform-queue job (called by the relay)
         * @param {string} id Job UUID (from GET /cloud-relay/queue/next or SQS message body)
         * @param {string} authorization Bearer &lt;connection api_key&gt;
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudRelayControllerDeliverJobResult(id: string, authorization: string, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudRelayJob>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudRelayControllerDeliverJobResult(id, authorization, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudRelayApi.cloudRelayControllerDeliverJobResult']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * slaops-cloud routes the request via the connection delivery_mode. direct: result is returned inline (completed immediately). relay-queue/platform-queue: job is pending — poll GET /cloud-relay/job/:id for the result.
         * @summary Submit a proxy job
         * @param {CreateCloudRelayJobDto} createCloudRelayJobDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudRelayControllerEnqueueJob(createCloudRelayJobDto: CreateCloudRelayJobDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudRelayJob>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudRelayControllerEnqueueJob(createCloudRelayJobDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudRelayApi.cloudRelayControllerEnqueueJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List relay connections for the authenticated user\'s tenant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudRelayControllerFindAllConnections(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CloudRelayConnection>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudRelayControllerFindAllConnections(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudRelayApi.cloudRelayControllerFindAllConnections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * For relay-queue mode, slaops-cloud syncs status from the relay on each poll. For platform-queue and direct modes, returns the stored job state.
         * @summary Poll for the result of a proxy job
         * @param {string} id Job UUID returned by POST /cloud-relay/job
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudRelayControllerGetJob(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudRelayJob>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudRelayControllerGetJob(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudRelayApi.cloudRelayControllerGetJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Vendor JWKS endpoint (used by relays and Aegis to validate platform JWTs)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudRelayControllerGetJwks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudRelayControllerGetJwks200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudRelayControllerGetJwks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CloudRelayApi.cloudRelayControllerGetJwks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CloudRelayApi - factory interface
 */
export const CloudRelayApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CloudRelayApiFp(configuration)
    return {
        /**
         * The relay polls this endpoint to claim jobs for legacy HTTP-polling connections. SQS-enabled relays (local-dev) receive jobs via SQS long-poll instead. Authenticate with the connection api_key as a Bearer token.
         * @summary Claim the next pending platform-queue job (called by the relay)
         * @param {string} authorization Bearer &lt;connection api_key&gt;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerClaimNextJob(authorization: string, options?: RawAxiosRequestConfig): AxiosPromise<CloudRelayJob> {
            return localVarFp.cloudRelayControllerClaimNextJob(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * For local-dev relays (type=local-dev), a dedicated SQS FIFO queue is provisioned automatically. The response includes sqs_queue_url and sqs_region.  tenantId and userId are read from the verified Cognito id_token — no client-supplied headers are trusted.
         * @summary Register a new relay connection
         * @param {CreateCloudRelayConnectionDto} createCloudRelayConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerCreateConnection(createCloudRelayConnectionDto: CreateCloudRelayConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<CloudRelayConnection> {
            return localVarFp.cloudRelayControllerCreateConnection(createCloudRelayConnectionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a relay connection and its SQS queue (if any)
         * @param {string} id Connection UUID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerDeleteConnection(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CloudRelayControllerDeleteConnection200Response> {
            return localVarFp.cloudRelayControllerDeleteConnection(id, options).then((request) => request(axios, basePath));
        },
        /**
         * After executing a claimed job, the relay posts the result here. Set `failed: true` to mark the job as failed.
         * @summary Deliver the result of a platform-queue job (called by the relay)
         * @param {string} id Job UUID (from GET /cloud-relay/queue/next or SQS message body)
         * @param {string} authorization Bearer &lt;connection api_key&gt;
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerDeliverJobResult(id: string, authorization: string, body: object, options?: RawAxiosRequestConfig): AxiosPromise<CloudRelayJob> {
            return localVarFp.cloudRelayControllerDeliverJobResult(id, authorization, body, options).then((request) => request(axios, basePath));
        },
        /**
         * slaops-cloud routes the request via the connection delivery_mode. direct: result is returned inline (completed immediately). relay-queue/platform-queue: job is pending — poll GET /cloud-relay/job/:id for the result.
         * @summary Submit a proxy job
         * @param {CreateCloudRelayJobDto} createCloudRelayJobDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerEnqueueJob(createCloudRelayJobDto: CreateCloudRelayJobDto, options?: RawAxiosRequestConfig): AxiosPromise<CloudRelayJob> {
            return localVarFp.cloudRelayControllerEnqueueJob(createCloudRelayJobDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List relay connections for the authenticated user\'s tenant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerFindAllConnections(options?: RawAxiosRequestConfig): AxiosPromise<Array<CloudRelayConnection>> {
            return localVarFp.cloudRelayControllerFindAllConnections(options).then((request) => request(axios, basePath));
        },
        /**
         * For relay-queue mode, slaops-cloud syncs status from the relay on each poll. For platform-queue and direct modes, returns the stored job state.
         * @summary Poll for the result of a proxy job
         * @param {string} id Job UUID returned by POST /cloud-relay/job
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerGetJob(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CloudRelayJob> {
            return localVarFp.cloudRelayControllerGetJob(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Vendor JWKS endpoint (used by relays and Aegis to validate platform JWTs)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudRelayControllerGetJwks(options?: RawAxiosRequestConfig): AxiosPromise<CloudRelayControllerGetJwks200Response> {
            return localVarFp.cloudRelayControllerGetJwks(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CloudRelayApi - object-oriented interface
 */
export class CloudRelayApi extends BaseAPI {
    /**
     * The relay polls this endpoint to claim jobs for legacy HTTP-polling connections. SQS-enabled relays (local-dev) receive jobs via SQS long-poll instead. Authenticate with the connection api_key as a Bearer token.
     * @summary Claim the next pending platform-queue job (called by the relay)
     * @param {string} authorization Bearer &lt;connection api_key&gt;
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cloudRelayControllerClaimNextJob(authorization: string, options?: RawAxiosRequestConfig) {
        return CloudRelayApiFp(this.configuration).cloudRelayControllerClaimNextJob(authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * For local-dev relays (type=local-dev), a dedicated SQS FIFO queue is provisioned automatically. The response includes sqs_queue_url and sqs_region.  tenantId and userId are read from the verified Cognito id_token — no client-supplied headers are trusted.
     * @summary Register a new relay connection
     * @param {CreateCloudRelayConnectionDto} createCloudRelayConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cloudRelayControllerCreateConnection(createCloudRelayConnectionDto: CreateCloudRelayConnectionDto, options?: RawAxiosRequestConfig) {
        return CloudRelayApiFp(this.configuration).cloudRelayControllerCreateConnection(createCloudRelayConnectionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a relay connection and its SQS queue (if any)
     * @param {string} id Connection UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cloudRelayControllerDeleteConnection(id: string, options?: RawAxiosRequestConfig) {
        return CloudRelayApiFp(this.configuration).cloudRelayControllerDeleteConnection(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * After executing a claimed job, the relay posts the result here. Set `failed: true` to mark the job as failed.
     * @summary Deliver the result of a platform-queue job (called by the relay)
     * @param {string} id Job UUID (from GET /cloud-relay/queue/next or SQS message body)
     * @param {string} authorization Bearer &lt;connection api_key&gt;
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cloudRelayControllerDeliverJobResult(id: string, authorization: string, body: object, options?: RawAxiosRequestConfig) {
        return CloudRelayApiFp(this.configuration).cloudRelayControllerDeliverJobResult(id, authorization, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * slaops-cloud routes the request via the connection delivery_mode. direct: result is returned inline (completed immediately). relay-queue/platform-queue: job is pending — poll GET /cloud-relay/job/:id for the result.
     * @summary Submit a proxy job
     * @param {CreateCloudRelayJobDto} createCloudRelayJobDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cloudRelayControllerEnqueueJob(createCloudRelayJobDto: CreateCloudRelayJobDto, options?: RawAxiosRequestConfig) {
        return CloudRelayApiFp(this.configuration).cloudRelayControllerEnqueueJob(createCloudRelayJobDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List relay connections for the authenticated user\'s tenant
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cloudRelayControllerFindAllConnections(options?: RawAxiosRequestConfig) {
        return CloudRelayApiFp(this.configuration).cloudRelayControllerFindAllConnections(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * For relay-queue mode, slaops-cloud syncs status from the relay on each poll. For platform-queue and direct modes, returns the stored job state.
     * @summary Poll for the result of a proxy job
     * @param {string} id Job UUID returned by POST /cloud-relay/job
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cloudRelayControllerGetJob(id: string, options?: RawAxiosRequestConfig) {
        return CloudRelayApiFp(this.configuration).cloudRelayControllerGetJob(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Vendor JWKS endpoint (used by relays and Aegis to validate platform JWTs)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cloudRelayControllerGetJwks(options?: RawAxiosRequestConfig) {
        return CloudRelayApiFp(this.configuration).cloudRelayControllerGetJwks(options).then((request) => request(this.axios, this.basePath));
    }
}

